### ISSUE TITLE
選字時不需使用方向鍵來左右移動游標的解決方案

### ISSUE THREAD

**Issue by icycandle** [openvanilla/McBopomofo#104]
過去新酷音曾經實作 jk 選字的功能，非常實用。想請教如果想在小麥注音加上 jk 左右移動游標的 feature，大概要從哪個 class 開始看？

又或者，在 mac 上面也許可以用 emacs 的風格（想想 jk 應該是 vim style xD），用 ctrl+a 到輸入區的起始位置， ctrl + e 到結束位置， ctrl + f & ctrl + b 來前後移動一個字元。

**Comment by icycandle** [comment]
試著自己先 hacking 看看實用性如何，晚點來回報心得
https://github.com/icycandle/McBopomofo/commit/8d595cadc9493cbfa02acb82b7fd9311de102199

**Comment by mjhsieh** [comment]
thanks, looking forward to your own test. j/k is vi's up/down by the way.

**Comment by AustinTing** [comment]
> 在 mac 上面也許可以用 emacs 的風格（想想 jk 應該是 vim style xD），用 ctrl+a 到輸入區的起始位置， ctrl + e 到結束位置， ctrl + f & ctrl + b 來前後移動一個字元。

@icycandle 這真的是很讚的提議，期待您hacking結果的分享。
我換小麥注音的理由是可以用 ctrl + f & ctrl + b 來移動編輯，如果連選字時都可以用這快捷建就真的太好了。

**Comment by zonble** [comment]
PR #219

**Comment by zonble** [comment]
已 merge ，先關票。
