### ISSUE TITLE
在輸入法選單中使用「小麥注音」取代「注音」作為名稱，避免與內建注音輸入法混淆

### ISSUE THREAD

**Issue by irvin** [openvanilla/McBopomofo#109]
![_2016_7_18_11_54](https://cloud.githubusercontent.com/assets/165936/16905817/a607bbec-4cde-11e6-8509-fcdd55516914.png)
![_ _new_issue_ _openvanilla_mcbopomofo](https://cloud.githubusercontent.com/assets/165936/16905884/e6819dfe-4cdf-11e6-89f9-cb575f3e1782.png)

如果同時開啟小麥與與系統內建注音輸入法，切換輸入法時會很難區別兩者

**Comment by timdream** [comment]
只裝一種注音輸入法的人不會遇到這個問題 ^^: 還滿好奇為何要裝這麼多注音輸入法

**Comment by irvin** [comment]
因為在 10.11 或 10.12 以上，可能是小麥使用的舊輸入法架構，會導致他在某些程式內無法使用，或某些狀況下特定輸入鍵盤會暫時失效

**Comment by mjhsieh** [comment]
可以告訴我，哪些程式內不能用，如果我有方法拿到的話我可以測試然後看看有沒有解法。

**Comment by ShikiSuen** [comment]
但在這之前也最好還請先給小麥注音使用「小麥注音」來命名。在相容性問題解決完畢之前，名稱混淆的問題應該沒有持續的必要才對。

**Comment by irvin** [comment]
@mjhsieh 大感謝！
