### ISSUE TITLE
Is there any plan for new version release?

### ISSUE THREAD

**Issue by PeterDaveHello** [openvanilla/McBopomofo#113]
As the latest release is about 2 years ago (0.9.6.11 (2014-10-28)), and there are many changes during this period, so I wonder if there is any plan for the new release? Thanks.

**Comment by mjhsieh** [comment]
Hi, we are working on it.

**Comment by asoksevil** [comment]
@mjhsieh That's good news. You think it would be possible to add some features from iOS and Android versions like word prediction and toneless inputting?

For instance instead of typing ㄊㄞˊㄅㄟˇ for Taipei you could just type ㄊㄅ or ㄊㄞㄅㄟ

Thanks for the hard work! Any ETA?

**Comment by mjhsieh** [comment]
對注音文還是有很大的抗拒...

**Comment by mjhsieh** [comment]
@PeterDaveHello see 57ad65f7a7903b2942b4c3fda757965160cf8b4c , we are now working on the build.

**Comment by mjhsieh** [comment]
@asoksevil please file an issue for that, but do note that we still need to prioritize the issues. We got too many issue, too much going on in our day jobs. @_@

**Comment by asoksevil** [comment]
@mjhsieh Actually I did open a new issue here back in Nov 11, 2015: https://github.com/openvanilla/McBopomofo/issues/95

I mean, I can wait there's no rush it's just that knowing how easy it's on cellphones I just wonder if there was a way to completely change computer typing because it is still quite archaic. You type way less key strokes.

**Comment by asoksevil** [comment]
@timdream made an awesome IME: https://timdream.org/jszhuyin/ it might be helpful to merge some of the work tim has done. I wish this was offline or for Mac.

**Comment by timdream** [comment]
@asoksevil It would be hard to convert McBopomofo (and with memory-consumption implications too) to run a JS-written engine. I don't know Mac programming well enough to know if there are other runner/IM framework that could do this.

**Comment by PeterDaveHello** [comment]
Thanks!

**Comment by ShikiSuen** [comment]
Good to see you people continued working on it.
