### ISSUE TITLE
屏棄 屏氣 兩個詞都有但是順序不對

### ISSUE THREAD

**Issue by timdream** [openvanilla/McBopomofo#117]
我覺得順序不對是因為「屏氣」幾乎都是四個字的使用：「屏氣凝神」，只輸入兩個音的時候應該要讓「屏棄」出現在前面。

Google search 的數量：

* 屏氣 -凝神 約有 221,000 項結果
* 屏氣 約有 415,000 項結果
* 屏棄 約有 250,000 項結果

可以改嗎？另外的問題是這樣要怎麼改 — 我不確定這樣人工調整數字是要設什麼數字好？

`phrase.occ`:

    屏氣	6
    屏氣凝神	5
    屏棄	1

**Comment by timdream** [comment]
或許可以改成：

    屏氣	1
    屏氣凝神	5
    屏棄	2

因為「屏氣」出現 6 次，有 5 次是在「屏氣凝神」裡(?)，然後要把「屏棄」拉高所以改成 2？

**Comment by mjhsieh** [comment]
我向來不直接人工調整數字，但是你剛剛提出來一的 weight 修正的概念, 這我們以前有想過，但是大規模實驗的時候結果不好。我先找個我可以不更動 algorithm 的前提下改 freq.

**Comment by mjhsieh** [comment]
"fixed" in https://github.com/openvanilla/McBopomofo/commit/d379b8f5844e6a1b308377cdd7a2725072b21b45

**Comment by timdream** [comment]
@mjhsieh 可以請教一下是怎樣的 fixed 了嗎？這三個詞的頻率並沒有修改。

```
 屏氣   6
 屏氣凝神       5
 屏棄	1
```

**Comment by mjhsieh** [comment]
屏棄	10
屏氣	6

I got this in d379b8f . 我的 fix 就是 corpus 多吃了一些有 屏棄 的文章.
