### ISSUE TITLE
缺字問題

### ISSUE THREAD

**Issue by carl0schen** [openvanilla/McBopomofo#118]
用macOS Sierra內建注音輸入法（未勾選顯示簡體字和罕用字）可以找到「畑」（ㄊ一ㄢˊ）、「坂」（ㄅㄢˇ）等字，小麥注音輸入法找不到。或者破音字其中一個讀音找不到，例如用小麥注音輸入法輸入「罕」（ㄏㄢˇ）找得到，輸入（ㄏㄢˋ）卻找不到。應該還有其他類似缺字問題，這方面不知怎麼回報或改進？

**Comment by mjhsieh** [comment]
在這邊提出來應該就夠了，我會處理。 Thanks.

**Comment by mjhsieh** [comment]
教育部重編國語辭典修訂版裡面罕沒有漢的音，可否請您提供資料來源？

**Comment by mjhsieh** [comment]
畑坂 在 trunk 裡面了。

**Comment by carl0schen** [comment]
macOS內建注音的漢的音會顯示出罕。
![mac](https://cloud.githubusercontent.com/assets/18241068/21035465/426ec750-bdfa-11e6-953b-3db82eb97b2c.jpg)

**Comment by mjhsieh** [comment]
研考會 - http://www.cns11643.gov.tw/AIDB/query_general_view.do?page=1&code=4b38
教育部 - http://dict.revised.moe.edu.tw/cgi-bin/cbdic/gsweb.cgi?o=dcbdic&searchid=W00000004874
wiki - https://zh.wiktionary.org/wiki/罕

都沒有這個讀音。

**Comment by carl0schen** [comment]
看起來是macOS內建輸入法的錯誤，謝謝。

**Comment by mjhsieh** [comment]
兩天前加入 畑, 坂 的 commit 是 096bd01add8e0bbb6f6b759346090515ef04f06a

**Comment by ShikiSuen** [comment]
@carl0schen 「罕」（ㄏㄢˋ）這個讀音其實是這樣的：大陸人經常唸「罕」（ㄏㄢ˙）輕聲，但某些省地的居民不習慣北京腔的輕聲結尾、只得將其唸成（ㄏㄢˋ）；而 macOS 的注音詞庫就音韻資料而言一開始是基於簡體拼音來完成的（經常會出現錯誤的用字搭配，當然最近幾年的 macOS 內建注音就此而言略有小改進、但仍不夠徹底），所以才會出現這種情況。

**Comment by carl0schen** [comment]
@ShikiSuen 原來如此，謝謝解釋其緣由。
