### ISSUE TITLE
傳統注音加關聯字功能

### ISSUE THREAD

**Issue by mjhsieh** [openvanilla/McBopomofo#120]
Request from jackyown@ptt, Windows 傳統注音有此功能，其實 iOS 的注音也有類似 interface.

**Comment by ShikiSuen** [comment]
這個功能很有必要，特別是需要徹底擺脫 macOS 內建注音的情況下。我在 #118 的回覆當中提到過 macOS 內建注音就音韻庫而言的先天缺陷。

**Comment by ShikiSuen** [comment]
覆議。另註：

OpenVanilla.app 是有這個功能的，卻需要依賴一個單獨的關聯字表。
要是能直接將 language model 當中的 phrases 當作關聯字表的話就好了。

**Comment by zonble** [comment]
目前在 #263 當中實作

**Comment by zonble** [comment]
已經 merge。
