### ISSUE TITLE
請問如何輸入全形空白？

### ISSUE THREAD

**Issue by Lifelong-Study** [openvanilla/McBopomofo#121]

**Comment by mjhsieh** [comment]
目前不行, 下一版會加上。以後大概是按、然後方向鍵選第一個。

**Comment by wildjcrt** [comment]
@mjhsieh 這張 issue 看來可以 close 了，發現目前 (0.9.8) 按 ` 的第一個已經是全形空白！
https://github.com/openvanilla/McBopomofo/blob/master/Source/Data/BPMFPunctuations.txt#L104
