### ISSUE TITLE
傳統注音微調小建議 （請幫忙）

### ISSUE THREAD

**Issue by dissib** [openvanilla/McBopomofo#123]
我不會程式，不曉得該怎麼修改程式碼，須要請作者或會程式的使用者幫忙教導

1. 選字字窗 如果選字選過頭，手必需要離開鍵盤使用滑鼠或觸控板點選選字字窗的《 或 》按鈕才能回到想要的選字頁面，很不方便。
希望能修改成使用空白鍵跳頁循環回選字頁的第一頁。 不要只卡在最後一頁，會比較方便。

2. 輸入注音進入到選字頁面後，目前只能使用 esc 鍵刪除要輸入的字
希望能使用 delete 鍵回到選字頁面前，輸入注音的狀態。

3. 標點符號的定義意按鍵
    shift + , （逗號）系統會出現選單 ，〈《︿︽    
    shift + .  (句號） 一樣會出現選單 。〉》﹀︾
希望能夠調整成 shift+, 及 shit+. 只有逗號跟句號就好。  其他的括號類都整合到按鍵 [ 及 ]  裡，以浮合常用的文語習慣，加快打字速度。
    shift + "  選單會是 ；  希望能改成 " 的符號，   shift+ctrl+" 出現 '
    將；符號整合到 shit+ctrl+: 

4. 其他功能類希望能讓使用者自訂選字字窗的顏色。目前系統是預設的白色，想要改成深灰色或黑色。反白輸入法的選字字窗，區分輸入法選字窗跟 word 或網頁背景。

謝謝

**Comment by carl0schen** [comment]
第三點我覺得不是問題，你按shift＋逗號，是直接顯示全形逗號＋下底線。
除非你按方向鍵的下才會顯示選單，否則不會出現，這點和macOS內建注音一模一樣（所有標點符號），個人覺得很方便。

當你打一整串句子＋全形標點符號時，下底線連接整串句子做確認和修正，假設shift＋逗號只出現逗號沒下底線，應該會有問題（例如句子打到逗號就斷掉）。如果單打一個標點符號，雖然看似要多按一個Enter鍵作確認，但是長期累積的使用習慣，反而是比較快（尤其是打整串句子影響最大）。

感謝 @lukhnos 指正，自己眼殘沒注意到標題是指傳統注音= =

**Comment by lukhnos** [comment]
dissib@ 所說的第三點是在傳統注音模式下特有的問題（標題是「傳統注音微調」）。

先講標點符號，希望關於 Shift + , 只出逗點這件事情：其實小麥的傳統注音，如果是用倚天鍵盤排列，Shift +, 確實只有一個選擇。至於為什麼其他鍵盤排列沒有這樣的待遇，那只能說是小麥開發者之間的習慣差異所致。:)

標點符號的問題，短期內最快的解法，是直接修改這個檔案：

```
~/Library/Input Methods/McBopomofo.app/Contents/Resources/data-plain-bpmf.txt
```

這個檔案可使用 Finder 的「前往 > 前往檔案夾…」，然後把上述檔名貼上去，就會看到該檔案。用文字編輯器打開，尋找 `_punctuation_Standard_` 這個字串，會看到以下段落：

```
， _punctuation_Standard_< 0.0
〈 _punctuation_Standard_< 0.0
《 _punctuation_Standard_< 0.0
︿ _punctuation_Standard_< 0.0
︽ _punctuation_Standard_< 0.0
```

這串定義的意思是說，「在標準排列模式中，按 < (也就是 Shift-,)，會出現這幾個候選字」（後面的 `0.0` 在此沒有特別意義，但不可省略）。如果將其修改只剩下一行，那打 Shift-, 時就只會出現一個標點符號。例如 `_punctuation_ETen_<` 就是這樣定義的。

至於按 " (Shift-') 所出的符號定義則是：

```
； _punctuation_Standard_" 0.0
```

亦可將其改為自己想要的符號。目前小麥不支援 Shift-Ctrl+" 這樣的符號組合，但或許需要的人可以找一個自己用得方便的字元，來作為選擇其他符號所用。

改完檔案後，要登出（或重新開機）才會生效。

長期說來，或許還是要有個專門用來修改該檔案的應用程式。

關於第一和第三點，這些輸入法行為見仁見智。例如像第二點，我記得是漢音預設的行為，但這是（很多年前）從 PC 換過來 Mac 使用者的抱怨之一。這類行為通常一做下去，就要有使用者介面變成可調整的設定，至少也要有個隱藏設定碼讓人可以透過終端機修改（小麥的選字窗字型就屬於有隱藏設定這一種）。第四點的話，希望選字窗有不同顏色，是否因為選字窗不容易辨認？如果將字體放大，能否達到類同的效果呢？

不過最主要，還是要修改程式。如果有朋友願意嘗試修改小麥的程式碼，我相信作者群會樂意指出要修改的地方。

**Comment by dissib** [comment]
非常謝謝 lukhnos  的說明～  

終於可以暫時改一下標點符號設定，讓標點符號比較貼近我自己的習慣了。 
目前是把 很少用的 _punctuation_Standard_ 項目刪掉， 只留自己常用的。


關於第四點的選字窗有不同顏色的設定是之前 Yahoo!KeyKey 的功能， 使用過後真的相當方便，會更快的看到選字窗的位置。
我之前也試過以調大選字窗的字級，但是效果還是不比 顏色反差 來得直接，還是需要一、兩秒的時間去。

我想這個的差別就有點類似 windows 的滑鼠遊標是 白色箭頭 放在 word 上 跟 mac 的滑鼠遊標是 黑色箭頭 放在 word 上 的差別 。

希望開發者能提供這些功能的設定讓有習慣的使用者可以勾選～ 

非常謝謝大家～

**Comment by zonble** [comment]
在最近的版本中，我們加上了反向自訂詞功能。一般的自訂詞是用來增加詞彙，反向自訂詞就是把不要的排除掉。

可以輸入法選單當中的「編輯排除的詞彙」功能，打開一個文字檔，然後輸入

```
〈 _punctuation_Standard_<
《 _punctuation_Standard_<
︿ _punctuation_Standard_<
︽ _punctuation_Standard_< 
```

存檔，然後按一下「重新載入使用者詞彙」即可生效。

先把這張票關了。
