### ISSUE TITLE
請問小麥輸入法會紀錄輸入內容嗎？

### ISSUE THREAD

**Issue by ym920823** [openvanilla/McBopomofo#127]
哈囉，我看過一些輸入法會紀錄我們輸入過的文字來改善選字精準度，不曉得小麥輸入法會紀錄輸入的內容嗎？謝謝！

**Comment by ShikiSuen** [comment]
這個功能應該是還在做、但卻沒有收入到對公眾發行的官方編譯版本當中。

**Comment by zonble** [comment]
Fixed in #207.
