### ISSUE TITLE
外接螢幕選字選單錯位

### ISSUE THREAD

**Issue by roytseng-tw** [openvanilla/McBopomofo#128]
當在外接螢幕的視窗上選字的時候
選字的選單會顯示在筆電螢幕的最上方
不會出現在字的旁邊

macOS Sierra 10.12.5
MacBook Pro 2016 with touch bar

**Comment by emil-wu** [comment]
Same issue here. Please help to schedule some fix of it. Many thanks for your effort.
- macOS Mojave 10.14.5
- MacBook Pro 2017 with Touch Bar
- Google Chrom 75.0.3770.100

**Comment by ShikiSuen** [comment]
@roytseng-tw @emil-wu 可否請二位抽空再用目前 master 分支最新的版本測試一下？（需要麻煩二位用 Xcode 重新編譯，scheme 選 McBopomofoInstaller，摁 CMD+R 編譯完成之後選安裝即可）。

P.S.: Zonble 近期有用 Swift 重寫過選字窗。

**Comment by lukhnos** [comment]
我們在發布 1.1 版的時候修正了這個問題: 6d610a717d853ce4e4fcda0682bfbfa80c95a4f6 。如果 2.0.1 版仍然有這狀況，請發新的 bug，並描述外接螢幕的配置。
