### ISSUE TITLE
調整標點符號順序

### ISSUE THREAD

**Issue by s1hon** [openvanilla/McBopomofo#129]
想請問一下，
在之前的版本似乎可以直接去Input Methods裡調整標點符號順序，
現在有辦法去更動嗎？ 要去哪邊更改呢？

**Comment by zonble** [comment]
預計接下來的版本的手動加詞功能上，可以拿到這個需求

wiki 上面先寫了說明 https://github.com/openvanilla/McBopomofo/wiki/%E4%BD%BF%E7%94%A8%E6%89%8B%E5%86%8A
