### ISSUE TITLE
打字時中英切換小bug

### ISSUE THREAD

**Issue by hugebirder** [openvanilla/McBopomofo#133]
你好我發現有個小bug 就是假如我在google網頁搜尋先按了注音符號 像是 ㄒ一 然後我發現應該是又搜英文字直接caps lock 切成英文打完英文剛才先打的ㄒ一 還會在 要先刪除我才有辦法整個打出去 希望有辦法改善不然有時候會卡卡的 謝謝嘍～

**Comment by zonble** [comment]
現在已經沒有這個問題，先關。
