### ISSUE TITLE
Iterm2下 小麥注音無法使用

### ISSUE THREAD

**Issue by RainJayTsai** [openvanilla/McBopomofo#136]
OS 版本： MacOS Sierra 10.12.6
小麥注音版本： 0.9.9
Iterm2版本： Build 3.1.5.beta.2

輸入法切到換到Iterm2下面會反灰無法使用

不知道有沒有解法可以解決此問題

**Comment by YuerLee** [comment]
請參考 #99

**Comment by RainJayTsai** [comment]
@passerbyid 
感謝,可以正常work了
