### ISSUE TITLE
能否能新增簡繁轉換的功能

### ISSUE THREAD

**Issue by RainJayTsai** [openvanilla/McBopomofo#137]
不知道有沒有辦法像香草輸入法一樣支援簡體繁體轉換的功能

**Comment by ShikiSuen** [comment]
有人提過了：
https://github.com/openvanilla/McBopomofo/issues/24
https://github.com/openvanilla/McBopomofo/issues/81
https://github.com/openvanilla/McBopomofo/issues/91
但都沒被理會。

**Comment by Antairez** [comment]
支持，Yahoo KeyKey輸入法可以用control + command + G迅速切換簡繁輸入，如果小麥也能做到，就會切換過來。

**Comment by ShikiSuen** [comment]
這裡有個優先順序問題。沒記錯的話，Repo主似乎好像認為比起這個還有更重要的功能要完成。

**Comment by lukhnos** [comment]
> 這裡有個優先順序問題。沒記錯的話，Repo主似乎好像認為比起這個還有更重要的功能要完成。

寫 code 解決問題，送 patch 解決問題，但在我看來，你認為用 passive agressive 的方式諷刺實際出力的人，比解決問題的優先順序來得高。:)

**Comment by ShikiSuen** [comment]
@lukhnos 我已經放棄這種方式了，因為太情緒化的手段可能會讓對方徹底放棄做某些事情。
我能做的就是放棄使用小麥注音，並且暫時忘卻、直到哪天相關功能被加回來。
另外我上一條回覆確實不是唬爛：
<img width="525" alt="image" src="https://user-images.githubusercontent.com/3164826/60610433-d27a5f80-9dfe-11e9-9629-b5881258f6e7.png">

**Comment by ShikiSuen** [comment]
@lukhnos 話說回來，既然你能看出我（至少曾經是）「認為用 passive agressive 的方式諷刺實際出力的人，比解決問題的優先順序來得高」，你應該是至少幾年來都在注意我在線上的與資訊電子或者軟體產品相關的討論、才得出這種結論的吧。被我用這種方式槓過的東西有很多，小麥注音完全排不上號。畢竟小麥注音是免費軟體，一切都是聽 Repo 主說了算，誰也沒權利強制要求，你說是不是？

（仔細想了一下，很可能你是 Apple 的人、且正好是在字型本地化相關的職位工作。只是可能。）

**Comment by hedgehog049** [comment]
支持，小麥確實不錯用，但是工作上需要切換繁簡體不方便～

**Comment by bigjimmy546** [comment]
很棒的輸入法，一樣希望那個增加繁簡體切換，謝謝

**Comment by ShikiSuen** [comment]
This push request from Zonble solves this issue:
https://github.com/openvanilla/McBopomofo/pull/167
