### ISSUE TITLE
打錯字？漢「音」輸入法？

### ISSUE THREAD

**Issue by HongJheLi** [openvanilla/McBopomofo#142]
在偏好設定頁面中，漢「音」輸入法的，是不是想表達漢「英」？
另外真的希望可以有 Shift 切換大小寫功能，對於常切換作業系統的人來說會很有幫助的，麻煩。

<img width="498" alt="default" src="https://user-images.githubusercontent.com/12004458/49123200-beafcd80-f2f2-11e8-8272-9b7776672917.png">

**Comment by zonble** [comment]
請參考 Wikipedia。

https://zh.wikipedia.org/wiki/%E4%B8%AD%E6%96%87%E8%BE%93%E5%85%A5%E6%B3%95

漢音輸入法是於1985年由松下電器技術開發公司周峻慧開發，是第一個拼音/注音兼具的智慧型輸入法。

**Comment by HongJheLi** [comment]
抱歉，失敬了～
一時忽略沒有去 Google 證實。
原來那是專有名詞...
