### ISSUE TITLE
英文輸入模式切換大小寫

### ISSUE THREAD

**Issue by phonygene** [openvanilla/McBopomofo#143]
不好意思我想請問在輸入法切換到英文模式時除了按shift一個一個打以外，要如何切換大小寫字母？
或是有快捷鍵的列表，或有人能告訴我關於一些控制的熱鍵要在哪裡看麼？感激不盡。

**Comment by zonble** [comment]
現在有二種英文輸入模式，可以透過選字改變大小寫。
