### ISSUE TITLE
關於簡體中文辭庫，我這樣 folk 出去是否算侵犯了這個 repo 的權益？

### ISSUE THREAD

**Issue by ShikiSuen** [openvanilla/McBopomofo#144]
整個輸入法的主程式部分並沒有變動，我只是將輸入法名稱由「McBopomofo」改成「McBopomofo_CHS」（爭取不與既有的小麥注音繁體中文版產生衝突）、且詞庫變成了簡體中文而已（雖然還是 big5 編碼處理，但原詞庫檔案都是 UTF-8 編碼、本身就可以處理簡體中文）。

P.S.: 我在想，要不要允許小麥注音以熱鍵切換繁體中文詞庫、然後將簡體中文詞庫獨立出來交給其他人來維護。畢竟兩岸就國語讀音而言的差異並不算小（「崖」在大陸唸「ㄧㄚˊ」）、且兩邊都有不同的漢字合併習慣（比如說台灣的「着」和「著」都合併到「著」）。單獨引入簡繁轉換模組的話，其準確率受到 OpenCC 本身特性的制約（至少我不認為足夠完美），且會增加程式修改與維護的工作量。但這不是說簡體版詞庫就不兼顧台灣讀音了，這方面的支援我不認為應該放棄，畢竟這套詞庫也會幫到在大陸上班的台灣人。

**Comment by ShikiSuen** [comment]
我 folk 的倉庫在此：https://github.com/ShikiSuen/McBopomofo_CHS

**Comment by lukhnos** [comment]
根據小麥注音的 [README.md](https://github.com/openvanilla/McBopomofo/blob/master/README.markdown):

> 本專案主要程式碼以及編譯後軟體採用 MIT License 釋出，使用者可自由使用、散播本軟體，惟散播本輸入法的原始碼時必須保持軟體完整原始碼、不得修改版權文字。

[Wikipedia 中文版](https://zh.wikipedia.org/wiki/MIT%E8%A8%B1%E5%8F%AF%E8%AD%89)是這樣翻譯的（我加的粗體）：

> 被授權人有權利使用、複製、**修改、合併、出版發行、散布、再授權**和/或販售軟體及軟體的副本，及授予被供應人同等權利，惟服從以下義務。
> 在軟體和軟體的所有副本中都必須包含以上版權聲明和本許可聲明。

所以 fork 出去更名後發布你自製的版本，沒有問題。
