### ISSUE TITLE
希望可以使用ESC來取消所有已輸入但尚未用enter確認的文字

### ISSUE THREAD

**Issue by popwee416** [openvanilla/McBopomofo#146]
希望可以使用ESC來取消所有已輸入但尚未用enter確認的文字
也就是一次取消(刪除)包含底線的文字(那些尚未使用 Enter來確認的文字)

建議可透過Preference來選擇是否啟用此功能(像是Yahoo Key Key或是微軟的新注音都有此功能或行為)

謝謝

**Comment by ShikiSuen** [comment]
這個功能對目前小麥引擎是否屬於剛需，我持疑問態度。不過這並不是要反對做這個功能就是了。

打比方說「是一個人」有「ㄕˋ ㄧˊ ㄍㄜˋ ㄖㄣ」和「ㄕˋ ㄧ ㄍㄜˋ ㄖㄣˊ」兩組發音。
用威注音詞庫敲的話，因為每個詞的權重的原因，「事宜個人」與「世醫個人」難免會自動出現。
這種情況下，就難免需要分雌性來摁 Enter 鍵斷詞、以借此避免這種需要選詞選字的情況。

結論就是：目前的小麥引擎也好、LibChewing 也好，整句輸入其實不存在。
（中州韻引擎對八股文的利用方法怎樣，我不清楚。不過中州韻並未明確要求八股文「必須與字詞音韻表一一對應」。）
