### ISSUE TITLE
希望使用 Delete 鍵刪除未選定的字（傳統注音）

### ISSUE THREAD

**Issue by iamjohnny** [openvanilla/McBopomofo#152]
我習慣使用傳統注音，候選字列表出現未選定的時候，無法使用 delete 鍵，希望可以增加這項功能。

譬如按下 "，"
![image](https://user-images.githubusercontent.com/5452311/80709212-82a01e00-8b1f-11ea-973b-bd5dd832dfdd.png)

這時候一定得按 ESC 鍵才能取消，希望 delete 鍵也能做到一樣的事。

**Comment by lukhnos** [comment]
1.0 版包含此修正: https://github.com/openvanilla/McBopomofo/releases/tag/1.0
