### ISSUE TITLE
希望輸入符號時，能自動選取第一個候選字（傳統注音）

### ISSUE THREAD

**Issue by iamjohnny** [openvanilla/McBopomofo#159]
在傳統注音模式，第一個候選字通常是不用選的，直接打下一個字就行了。
不過，如果接著打符號，目前的情況是一定要先選第一位候選字，否則會無法繼續、出現警告音。

舉例來說，當我想打「好球」，我鍵入的是「ㄏㄠˇㄑㄧㄡˊ (2) 」，「好」這個字是第一候選字，不用按 (1) 選字。
<img width="73" alt="CleanShot 2020-10-29 at 05 59 17@2x" src="https://user-images.githubusercontent.com/5452311/97501223-e78fe000-19ab-11eb-9089-58c10abc997c.png"> <img width="84" alt="CleanShot 2020-10-29 at 06 04 21@2x" src="https://user-images.githubusercontent.com/5452311/97501653-9cc29800-19ac-11eb-816e-6998ede910b1.png">
但當我打「好。」的時候，目前需要鍵入「ㄏㄠˇ (1) 。」

一樣是在第一候選位置，「好」必需先選字才能接著打下去。

希望能在兩種輸入「好」的情境，有更一致的體驗。

這個需求可能和最近解決的 #152 有些相像。

**Comment by zonble** [comment]
仔細一看這邊有個問題，在傳統注音輸入法下，<> 其實這兩個按鍵已經被定義成換頁了。
