### ISSUE TITLE
中英文混合輸入 / 選字

### ISSUE THREAD

**Issue by bm2amb** [openvanilla/McBopomofo#162]
首先謝謝提供這個好用的軟體，在此之前我都是一直使用奇摩輸入法跟早期的自然輸入法。

在這兩個輸入法打中文時可以按著Shift 鍵輸入英文，而不需要將當前的字給完成

例如：  這個bopomo輸入法很好用 <=整串可以 輸入 「這個[Shift + bopomo]輸入法很好用」一次輸入。

選字時，如果可以用左右鍵切換上一組(頁)/下一組(頁) 就更完美

**Comment by zonble** [comment]
目前已經實作輸入英文字母，直接在輸入中文時按住 Shift 與字母即可。
