### ISSUE TITLE
增加文字庫內容

### ISSUE THREAD

**Issue by hm-yang** [openvanilla/McBopomofo#163]
感謝提供了一個這麼好用的輸入法
但是目前有個困擾
請問要怎麼在字庫內增加字呢? 還是只能透過git上的增加
需要增加"珉"這個字

謝謝

**Comment by lukhnos** [comment]
確實目前只能透過修改詞庫原始資料，才能增加新字詞: https://github.com/openvanilla/McBopomofo/tree/master/Source/Data

如果是新字的話，應該至少得修改 `BPMFBase.txt`，但是我記得目前的 build script 特別只允許原本就在 Big5 字集中的字。這一點得要先加入新字，再測試看看了。

@mjhsieh

**Comment by ShikiSuen** [comment]
What about allowing the build script to allow all unicode characters?

**Comment by hm-yang** [comment]
Hi, 

感謝,
我先試著修改BPMFBase.txt在local build, 看起來是可以的
只是變成未來如果有版本更新時都要自己重新修正而已 :)
或是可以考慮增加一個customized的字庫檔?

Thank you very much!!!!!!

**Comment by ShikiSuen** [comment]
@hm-yang 澄清兩點：

一、目前小麥注音倉庫 source/data/ 目錄下的 @mjhsieh 詞庫編譯系統（由 makefile 驅動）是支援萬國碼的。這套系統之前曾經僅支援 big5，但現在已經無所謂了。等你懂 python 了之後可以看一下 cook.py 等被 makefile 動用過的 python 腳本的內容。至於 BPMFBase 當中的內容，每一列原則上只需要漢字與注音就夠了（雖然 python 腳本內還是會有完整性檢查，可以手動移除之）。

二、由於 @zonble 近期引入了與微軟新注音、TSF新酷音、雅虎奇摩注音相同的「用 shift 鍵新增用戶自訂語彙」的功能（該不會奇摩注音的這個功能就是 zonble 寫的？），您又多了一個選擇：「~/Library/Application Support/McBopomofo/data.txt」裡面可以按照每行這個順序格式來新增漢字讀音：「字」「ㄧㄣ」「-1.0」。格式呈現如下：
```
屌 ㄉㄧㄠˇ -1.0
```
第三欄的數字不見得非得是「-1.0」，其絕對值越靠近 0、權重便越大。
編輯完畢且存檔之後，在輸入法選單內重載自訂語彙即可。

P.S.: 該功能為目前小麥注音倉庫新增的功能，需要辛苦您自行下載 30 多 GB 的 Xcode 自己重新編譯一份。屆時直接將 scheme 選成「McBopomofoInstaller」再編譯就行了。

---

@zonble 這個 issue 或許可以關掉了。
