### ISSUE TITLE
希望可以多一個選項來切換是否「使用大寫鎖定鍵切換輸入法/英數字鍵盤」

### ISSUE THREAD

**Issue by Fightsea** [openvanilla/McBopomofo#164]
我本身不喜歡用Caps切換中英文，有時誤按到會導致打字流暢度被中斷。
希望可以在GUI上多一個選項來控制是否「使用大寫鎖定鍵切換輸入法/英數字鍵盤」。
感謝。

**Comment by lukhnos** [comment]
用 Caps Lock 切換中英文輸入是 macOS 控制的。這個功能可以從系統偏好設定來關閉：

 > 系統偏好設定 > 鍵盤 > 輸入方式 > 「使用大寫鎖定鍵來切換上次使用的拉丁輸入方式及目前輸入方式」
