### ISSUE TITLE
命令行組譯失敗（macOS 12 + Xcode 13）

### ISSUE THREAD

**Issue by ShikiSuen** [OpenVanilla/McBopomofo#166]
[終端機輸出記錄.txt](https://github.com/openvanilla/McBopomofo/files/7510615/default.txt)

**Comment by ShikiSuen** [comment]
這是直接使用原版的程式碼包組譯時的終端輸出結果。

**Comment by ShikiSuen** [comment]
<img width="1342" alt="圖片" src="https://user-images.githubusercontent.com/3164826/141069154-2a0ad989-e613-4ea3-a7a7-7971d0fdede8.png">

**Comment by zonble** [comment]
請試試看 xcodebuild -scheme McBopomofo -configuration Release

**Comment by ShikiSuen** [comment]
@zonble 我在 Xcode 改了半天，禁用了與線上更新檢查有關的幾句程式碼（因為 NSURLConnection 我不知道如何改成 NSURLSession），瞎貓碰死老鼠根據 Xcode 的 deprecation 提示改掉了所有被 deprecated 的語法內容，才勉強通過編譯。

![ED48E0FEB925024EF005AA818EDC2D6C](https://user-images.githubusercontent.com/3164826/141147604-294db028-8cac-431a-a4bc-d786803723ff.jpg)

目前命令行編譯一切正常，用的就是您的語句（travis 腳本裡面有寫）。

P.S.: 剛剛有看到您的 push request。實在太感謝了。那我弄的純簡體中文版小麥注音或許可能就不需要了。
（光是將「著」與「着」區分開就害我捯騰詞庫捯騰很久。）

P.P.S.: 奇摩注音要是能被重新拾起來、換掉有授權爭議的組件之後繼續發揚光大的話就幸運了。雖然現在是不死小強，但目前這樣註定活不過 Universal Binary 2 被撤掉的那一天。Apple 很固執，堅決不給 macOS / iOS 做原廠的純簡體中文的注音輸入法。

**Comment by ShikiSuen** [comment]
剛剛仔細想了一下。要是想在新的 macOS + 新的 Xcode 組合環境下組譯目前的程式碼（我用的是跟著 release 同時發行的程式碼包）的話，由於構建目標是 macOS 10.10 Yosemite，所以需要在系統內使用諸如 XCodeLegacy 腳本這樣的東西來安裝 macOS 10.10 SDK。但因為根證書過期等原因，這款 SDK 在不修改電腦系統時間的前提下很可能是無法正常安裝的，就會比較麻煩。

以上只是我的推論。我主業也不是程式師，只是之前自己嘗試過編譯 SDLPal 專案、在當時積累了一點點小經驗而已。
