### ISSUE TITLE
[3147e1e] 無法摁「CTRL+SemiColon」輸入全形的分號。

### ISSUE THREAD

**Issue by ShikiSuen** [OpenVanilla/McBopomofo#168]
https://github.com/openvanilla/McBopomofo/commit/3147e1e20ffec91864782433c72c008868b2d805
我是用這個版本的源碼組譯的。系統 macOS 12 + Xcode 13。
用內建的 travis 腳本成功組譯。
然後我就發現不知道該怎樣用這個版本輸入全形分號了。

P.S.: 要是在每次簡繁轉換時在系統右上角有（類似奇摩輸入法那樣的）浮動視窗提示的話就好了。

**Comment by zonble** [comment]
小麥注音從一開始就沒有加上 Ctrl  的輸入按鍵，在小麥注音裡頭，全型分號是對應到 shift + " 上。

**Comment by ShikiSuen** [comment]
@zonble 感謝您的解答。（OV 那邊關於視窗邊框的也一並在此謝過。）
我記得 OV 引擎本體是支援基於 CTRL+ALT 的按鍵的（Punctuation 清單當中有相關組合按鍵的定義，實際上我倒是沒怎麼測試過）。McBopomofo 這邊將這套按鍵組合取消了，可是因為有什麼疑慮嗎？
