### ISSUE TITLE
Mcbopomofo is disabled

### ISSUE THREAD

**Issue by vwu** [OpenVanilla/McBopomofo#175]
Mcbopomofo is disabled today.
macOS Monterey 12.0.1.
McBopomofo Version 1.0 (846).

**Comment by ShikiSuen** [comment]
預設目錄不放到「/Library/Input Methods」下就是不行。
「~/Library/Input Methods」一定會出權限問題。

**Comment by vwu** [comment]
sudo mv ~/Library/Input\ Methods/McBopomofo.app /Library/Input\ Methods/ 
重新開機(Restart) 還是不行
關機然後開機 還是不行
去加了倚天注音 結果就OK了
把倚天注音刪了還是可以
