### ISSUE TITLE
關於自建新詞庫的幾個問題

### ISSUE THREAD

**Issue by ShikiSuen** [OpenVanilla/McBopomofo#176]
我最近正在忙於重新從頭打造一套詞庫。
https://github.com/ShikiSuen/vchewing-lingual-data/tree/main/imedata/mcbopomo
然而我在實踐過程當中發現了一些問題沒搞明白。
一、敲字時自動蹦出來的單字怪怪的、得自己親自點開候選鍵去選。
二、我不知道 BPMFBase 裡面小麥注音原廠的漢字順序是故意的還是隨便排的、是否會對字的候選頻率順序造成影響。
三、目前我的詞頻數據暫時還是用小麥注音的，但是字頻數據取自下面這個網站的六大數據源的詞頻總和：
https://coct.naer.edu.tw/tools/
然後有些讀音的字頻就怪怪的……
![image](https://user-images.githubusercontent.com/3164826/143487504-a50df478-4b9a-4945-bdbe-69a3b1bbf24d.png)
是說詞頻數據必須用 MJHsieh 在 Data 資料夾內留下的各種 python 腳本來生成嗎？
這些腳本是不是針對 python2 寫的、是不是對 python3 不相容？

**Comment by ShikiSuen** [comment]
補遺一下：萬一要是不想回答的話，請務必講出來。這樣我也就不用等。
好像經常有台灣人喜歡這樣。其實會很容易給對方留下「裝禮貌」的印象。
有些禮貌是假禮貌，會就這樣對對方的耐心等待持續「放置 PLAY」。

**Comment by zonble** [comment]
1. 目前候選字是按照語言模型中的詞頻排序，可以參考 Node.h 裡頭的實做https://github.com/openvanilla/McBopomofo/blob/6d610a717d853ce4e4fcda0682bfbfa80c95a4f6/Source/Engine/Gramambular/Node.h#L87-L111
2. 我看了一下你建立的[詞頻表格](https://raw.githubusercontent.com/ShikiSuen/vchewing-lingual-data/main/imedata/mcbopomo/phrase-chs.occ)，裡頭出現的頻率像這樣
```
拟	47112
你	32829
旎	52
鉨	0
薿	0
擬	0
妳	0
```
以這樣的頻率出現上圖中的候選字列表，看起來沒有什麼不正常的地方。

3. 我看了一下你的發文時間，是在晚上兩點，接下來則是在下午四點，基本上對於一個台北的上班族來說，這是一段從正常睡眠時間到勞動契約上的上班時間，對於一些在北美的夥伴來說，11/25 則是要與家人團聚的感恩節時間。

**Comment by ShikiSuen** [comment]
@zonble 感謝您的答覆。
看樣子只用平面媒體的數據的話仍舊會有明顯偏差。

MJHsieh 的情況我不是很知情，猜想他做生物科研會忙到爆。倒是我這個誤會是對楊老師您產生的。
多年前短暫加過您臉書，嘗試與您聊一些與 macOS 預設中文字型有關的問題，卻無論怎樣傳訊息都沒被回覆。
我不太擅長應對這種情況，因為會無休止地自我檢討自己有沒有哪裡搞砸。
這種無休止的自我審查的感覺之前曾經有過，長達好幾年的經歷，直接被憋出 PTSD。

不過當年後來我寫了篇爛文來普及「為什麼華文黑體必須要被換掉」「為什麼蘋方是好選擇」。

再後來，多年之後，您維護的雅虎奇摩注音安裝程式的 github repo 那邊我有 pull request 了一套新的 icon。
又被您無視了。

但既然您現在專門來答覆，那就證明了我之前對您確實都是誤會。
於是我在這裡 就我當年介紹蘋方的那篇文章當中有關「遺志」這個詞的使用 向您致歉。
（好像這個詞當年被 PTT 網友吐槽過，所以我當時改掉了。）

**Comment by ShikiSuen** [comment]
我先關掉這個 case。
順便 爛文地址：https://zhuanlan.zhihu.com/p/20096331
