### ISSUE TITLE
毫米與公釐，以及各種度量單位符號的大陸唸法

### ISSUE THREAD

**Issue by ShikiSuen** [OpenVanilla/McBopomofo#181]
我的 fork 被洗過 commit history 所以無法正常 pull request，就放到這邊來。
各位 maintainers 合併過之後可以關掉這個 issue 討論串。

相對於 https://github.com/openvanilla/McBopomofo/pull/179/commits/0093144913c40b23c8b99518dd6a0bcef59f1ffd 更新過的 Symbols.txt 而言，這次新增：

㎠ ㄆㄧㄥˊ-ㄈㄤ-ㄌㄧˊ-ㄇㄧˇ -8
㎡ ㄆㄧㄥˊ-ㄈㄤ-ㄇㄧˇ -8
㎟ ㄆㄧㄥˊ-ㄈㄤ-ㄍㄨㄥ-ㄌㄧˊ -8
㏒ ㄉㄨㄟˋ-ㄕㄨˋ -8  // MJHsieh 更新了這筆读音 
㎤ ㄌㄧˋ-ㄈㄤ-ㄌㄧˊ-ㄇㄧˇ -8
㎥ ㄌㄧˋ-ㄈㄤ-ㄇㄧˇ -8
㎝ ㄌㄧˊ-ㄇㄧˇ -8
㎜ ㄏㄠˊ-ㄇㄧˇ -8
¥ ㄖㄣˊ-ㄇㄧㄣˊ-ㄅㄧˋ -8

以下項目新增與否，看諸位 maintainers 心情。

ㄋㄟㄋㄟ ㄋㄟ-ㄋㄟ -8
🐂🍺 ㄋㄧㄡˊ-ㄅㄧ -8
🐃🍺 ㄋㄧㄡˊ-ㄅㄧ -8
🐄🍺 ㄋㄧㄡˊ-ㄅㄧ -8
🐮🍺 ㄋㄧㄡˊ-ㄅㄧ -8
🦏🍺 ㄋㄧㄡˊ-ㄅㄧ -8

以上。

**Comment by ShikiSuen** [comment]
（請在修復該問題且推送至 Master 之後關掉這個討論串。謝謝合作。）

**Comment by zonble** [comment]
@ShikiSuen 我覺得這個用自訂詞應該就可以滿足了吧？

**Comment by ShikiSuen** [comment]
可以。
威注音詞庫已經收錄了這些條目。本來這些條目收錄與否、都是自由的。

P.S.: ㄋㄟㄋㄟ除外，要求必須 BPMFBase 有至少一個漢字唸 ㄋㄟ 才能敲出來。
我給 奶 這個字加上了這個音之後，`ㄋㄟㄋㄟ ㄋㄟ-ㄋㄟ -8` 這條才生效。
不過 用戶自訂語彙應該可以支援這個功能吧……我還沒測試。
