### ISSUE TITLE
請勿誤用「妺（ㄇㄛˋ）」。

### ISSUE THREAD

**Issue by ShikiSuen** [OpenVanilla/McBopomofo#185]
@mjhsieh 請清查一下 phrase.occ 與 BPMFMappings.txt 清理一下這個漢字的誤用形。
（Google 倒是有不少相關的檢索結果。竊以為可能是用倉頡等筆形輸入法敲字時敲錯字所致。）

萌典（MOE 教育部詞典的克隆版本）：
![image](https://user-images.githubusercontent.com/3164826/143732227-a56c56dc-cb76-48cd-b2e5-23dfe198b93b.png)
![image](https://user-images.githubusercontent.com/3164826/143732229-658acf5b-31a9-4cb4-888a-3e4921451149.png)

陳五南國語詞典：
![image](https://user-images.githubusercontent.com/3164826/143732239-017b4ab0-8a84-4c3f-9801-ddeb96a0f611.png)

牛津現代漢語規範詞典（簡體中文）：
![image](https://user-images.githubusercontent.com/3164826/143732255-e8dd0f97-7d73-4caa-b331-c92996d59a9d.png)

**Comment by ShikiSuen** [comment]
（請在修復該問題且推送至 Master 之後關掉這個討論串。謝謝合作。）

**Comment by mjhsieh** [comment]
This one likely was an OCR error since day one.
