### ISSUE TITLE
python2 -> python3

### ISSUE THREAD

**Issue by ShikiSuen** [OpenVanilla/McBopomofo#189]
這裡附上所有針對 python 3 升級過的下述詞庫維護腳本：
```
bpmfmap.py
buildFreq.py
cook-plain-bpmf.py
cook.py
count.occurrence.py
nonCJK_filter.py
self-score-test.py
```
[Python3_Version.tar.gz](https://github.com/openvanilla/McBopomofo/files/7641449/Python3_Version.tar.gz)

**Comment by ShikiSuen** [comment]
用 python 3.9 測試通過。

P.S.: 從下一版 macOS 開始就不再隨贈 python 了，要不要考慮換用執行效率更高的 perl？

**Comment by zonble** [comment]
小麥改了詞庫格式，這些應該不相容了。新的詞庫建立工具也已經改用 Python 3。
