### ISSUE TITLE
「與會」的「與」應該改成去聲。

### ISSUE THREAD

**Issue by ShikiSuen** [OpenVanilla/McBopomofo#191]
「與」作為「參與」的「與」使用時，音調應為去聲。

![image](https://user-images.githubusercontent.com/3164826/144700571-d8a25b7b-8f4a-49e2-99b9-1aed543de9ed.png)

![image](https://user-images.githubusercontent.com/3164826/144700604-b107ccfc-1501-4b83-b3de-9edd28b57a03.png)

**Comment by ShikiSuen** [comment]
P.S.: 這問題導致「語彙」這個詞無法優先輸出。

（該問題解決完了就可以關掉了。）

**Comment by zonble** [comment]
這個詞其實台灣大多數人不是照教育部的念法的，可以參考一下這段新聞中的念法。

https://www.youtube.com/watch?v=mmLkELaSCf0

**Comment by ShikiSuen** [comment]
@zonble 那就保留做相容處理吧。

（二十年前的標準的話，在 CCTV 的主持人唸錯一個字扣 250NTD。不知現在的罰款標準上漲到多少了。）
