### ISSUE TITLE
有沒有辦法換回 macOS 內建的 IMK 選字窗格？

### ISSUE THREAD

**Issue by ShikiSuen** [OpenVanilla/McBopomofo#194]
https://github.com/mzp/EmojiIM/pull/8
根據這篇文章來看，IMK 的選字窗格在美工方面（以及功能性方面）應該已經遠超 Voltaire 了。
至少在橫向布局時可以一次性拉出好幾行候選字（以系統內建的注音輸入法為例）。

我只是對方法毫無頭緒而已。
如果 McBopomofo 官方專案這邊沒有相關計畫的話、不打算這樣做的話，请講。
屆時我會考慮去為威注音在這方面的功能的實現而請外援，因為我並無相關的知識實力。

**Comment by zonble** [comment]
據我所知，小麥就只是幾個人在本業以外的小專案，大概是在真的很有餘裕，或是某次 macOS 改版搞到小麥完全沒辦法用的狀況下，才有辦法改那麼點東西。真要說起來，整個小麥輸入法大概都沒有什麼整體開發計畫或 roadmap 之類的東西，也沒有什麼要跟誰比較的意圖。

話說如果只是要享受 IMK 的選字窗的話，其實只需要改用 macOS 內建的輸入法就好了。另外我其實會鼓勵大家動手來玩玩看，code 就在那邊，我還沒見過那個人一開始就會寫輸入法。

**Comment by zonble** [comment]
你想要抽換選字窗的實作的話，就是修改 `-_showCandidateWindowUsingVerticalMode:client:` 

https://github.com/openvanilla/McBopomofo/blob/f7a24862c4e1733a2264b56e434d1a449325d769/Source/InputMethodController.mm#L1355

**Comment by ShikiSuen** [comment]
@zonble 感謝您的講解。

剛剛有分析了一下和碼輸入法，發現 IMK 並不只是換兩三行源碼那樣簡單。
https://github.com/HeChinese/OpenHeInput-MacOS

要是你們有 paypal 捐贈方式就好了，我可以考慮請你們喝咖啡 XD 看你們是否樂意抽時間方便幫忙。
（這種事情對我而言還真是跨行業燒腦筋……）
