### ISSUE TITLE
heterophony1.list 是不是無法同時推舉某個漢字的多個破音？

### ISSUE THREAD

**Issue by ShikiSuen** [OpenVanilla/McBopomofo#195]
以這個版本的威注音詞庫為例子（僅套用 heterphony1.list）：
（需要用 makefile 才能生成 data.txt，這個過程會自動將 components 資料夾下的內容拼裝成小麥注音可用的 BPMFBase BPMFMapping 以及 Phrase.occ 這三個檔案、且自動去重複＋自動疊加重複的字詞頻＋自動將漢語拼音轉注音。）
https://github.com/ShikiSuen/vchewing-lingual-data/tree/57dd5c07281ca4937541d0adf35da0ed913be407/imedata/mcbopomo/Data-CHT

「和」在兩岸總共有七個讀音：
```
和 ㄏㄢˋ // heterophony1.list
和 ㄏㄜˊ // heterophony1.list
和 ㄏㄜˋ // heterophony2.list
和 ㄏㄨˊ // heterophony2.list
和 ㄏㄨㄛˋ // heterophony2.list
和 ㄏㄨㄛˊ // heterophony2.list
和 ㄏㄨㄛ˙ // heterophony3.list
```

前兩個讀音在兩岸最常用。（陸歸審音沒有「ㄏㄢˋ」，臺規審音沒有「ㄏㄨㄛˊ 」。）
我對這些讀音的 heterophony 清單規劃如上。

然而，這樣配置之後，heterophony 1 的超優先權似乎只對「ㄏㄢˋ」生效。
至少，「ㄏㄜˊ」這個讀音在 heterophony1.list 當中的登記並未使其在「ㄏㄜˊ」讀音表內佔據絕對優先的位置。
我甚至還要往下翻一頁。

相關 data.txt 內容如下：
```
和 ㄏㄜˊ -6.800000
和 ㄏㄜˋ -6.800000
和 ㄏㄢˋ -5.08059193
和 ㄏㄨˊ -6.800000
和 ㄏㄨㄛˊ -6.800000
和 ㄏㄨㄛˋ -5.773739
和 ㄏㄨㄛ˙ -6.466886
何 ㄏㄜˊ -5.18820327
```

我實在搞不明白究竟哪裡出了問題。

**Comment by zonble** [comment]
你看一下 cook.py

https://github.com/openvanilla/McBopomofo/blob/master/Source/Data/bin/cook.py#L13-L15

```
bpmf_phon1 = {}
bpmf_phon2 = {}
bpmf_phon3 = {}
```

heterophony1.list、heterophony2.list、heterophony3.list 會被讀進這三個 dictionary 裡頭。dictonary 就是 Python 裡頭的 key/value 的結構。如果你想要支援三個音以上的破音字，需要 heterophony4.list... 並且改寫 cook.py。

**Comment by ShikiSuen** [comment]
@zonble 感謝講解。

看樣子每個 heterophony 檔案當中一個漢字只能寫一個讀音，否則只會認隨機的某一個（或者引發錯亂）。
（如果我有講錯的話，歡迎指正。）

這些內容我先記下來，回頭找人將這些工具用 rust 重寫成 binary 時再引入這些改進。

**Comment by ShikiSuen** [comment]
已圓滿解決。再次感謝 zonble 老師。

https://github.com/ShikiSuen/vchewing-lingual-data/commit/93e573d20a75a3ab2cab507b4e967791d6244628

**Comment by ShikiSuen** [comment]
剛才我發現另一個問題，在這裡補記一下。
macOS 內建的 python2 是 UCS2 的。
MacPorts 安裝的 Python3 預設情況下是 UCS4。
這可能會影響 cook.py 對字元長度的判斷、導致該腳本在某些情況下無視某些漢字。

抄送 @mjhsieh @zonble ，估計這條提醒會在諸位將來正式使用 python3 的時候用得到。

**Comment by ShikiSuen** [comment]
![image](https://user-images.githubusercontent.com/3164826/144959013-868ed141-d3a2-4daa-a6b6-1b8e7be981b4.png)
