### ISSUE TITLE
孬 的實際讀音是 ㄋㄠ-。

### ISSUE THREAD

**Issue by ShikiSuen** [OpenVanilla/McBopomofo#197]
MOE 全字庫內查到這個漢字只有「ㄋㄠ-」這一個讀音。
重編國語辭典（萌典）也只標注了這個音：
![image](https://user-images.githubusercontent.com/3164826/145512817-c4069ec4-a23b-4041-aaaa-c675fb2aed78.png)
陸規《通用規範漢字表》內也是這個審音：
![image](https://user-images.githubusercontent.com/3164826/145512999-daf1bafb-d686-4652-a629-3cdb6fd1f4e0.png)

於是「孬」的「ㄏㄨㄞˋ」讀音，可以考慮如下兩種處理方法：
一、直接從 BPMFBase 砍掉（威注音直接砍了這條讀音）。
二、考慮到這個讀音可能是 @mjhsieh 主動加上去的，於是可以將「孬」的「ㄋㄠ-」讀音放到 heterophony1.list。這樣可以讓「孬」的「ㄏㄨㄞˋ」讀音自動降頻。

![image](https://user-images.githubusercontent.com/3164826/145512787-7b7e061b-1a8d-4f75-9b64-0d1a02e9402e.png)

**Comment by mjhsieh** [comment]
This likely is not from me.

**Comment by zonble** [comment]
It was libtabe. 

https://github.com/kcwu/libtabe/blob/master/tsi-src/tsi.src

You can also find it in Going input method.
