### ISSUE TITLE
背革裝「ㄅㄟ」要不要考慮改成「ㄅㄟˋ」？

### ISSUE THREAD

**Issue by ShikiSuen** [OpenVanilla/McBopomofo#198]
畢竟此處的「背」不是動詞。

**Comment by zonble** [comment]
感覺這個詞根本就是日文吧？

**Comment by ShikiSuen** [comment]
和製漢語。

**Comment by ShikiSuen** [comment]
其實，和製漢語逆向輸出到現代漢語當中的例子，從清朝末期開始就沒斷過。
在制定對應的審音的時候，就得考慮每個字的詞性。
「武蔵野」的「藏」，有人唸「ㄗㄤˋ」，有人唸「ㄘㄤˊ」。我只知道大陸這邊僅唸「ㄗㄤˋ」。
「會社」的「會」應該遵循「會計」的「會」的讀音的，但因為唸成本來讀音的人群比例實在太多，只能作罷。

**Comment by mjhsieh** [comment]
Seriously, have anyone used this phrase?

**Comment by ShikiSuen** [comment]
@mjhsieh Certain people will use this phrase when someone wants his friends in Japan to help him / her buy a book with leathered cover. In that case, the word "背革裝" must be used if that is the wanted cover.
