### ISSUE TITLE
「學」不唸「洨」。

### ISSUE THREAD

**Issue by ShikiSuen** [OpenVanilla/McBopomofo#199]
https://github.com/openvanilla/McBopomofo/blob/master/Source/Data/BPMFBase.txt#L11819

![image](https://user-images.githubusercontent.com/3164826/145562207-21e5d72f-9ed7-46cb-8e34-33faf07b0648.png)
=====
全字庫、MOE 重編國語辭典、以及大陸的通用規範漢字審音裡面都沒有這種唸法。
![image](https://user-images.githubusercontent.com/3164826/145562361-f0e859e6-c336-4289-8fab-1f46b146bc71.png)

**Comment by zonble** [comment]
教育部在 2012 年之前，讓「學」的兩種讀音並存，但是 2012 年時併讀。你看到的是現在國語詞典上的資料，但教育部合併不代表就沒有人不會繼續這麼念，大概除了在學學生，大概沒什麼人會鳥教育部，誰平常會去關心教育部改了哪個讀音。我也不覺得教育部改了什麼，輸入法就得跟著改，就沒有人在乎教育部，也沒有人會想為了教育部改變自己的習慣。

這個音的目前主要會用在特別誇大、並且有點諷刺的語氣中，像是「你查了好多字典，好有ㄒ一ㄠˊ問喔～」。

跟台灣讀音變化有關的資料可以去字音查訊系統看看，這是一個國中老師從一字多音審訂表建立的資料庫

http://area.hcjh.tn.edu.tw/noise/e-book-92/view.asp?articleid=20030608150609&Discuss=book01&Page=1

**Comment by ShikiSuen** [comment]
@zonble 那這問題在小麥注音可能需要 heterophony.txt 來解決吧。
既然有留存價值，那就先結案。

P.S.: 我忘了一點：越是陸規審音的辭典當中規定不讀哪個音，這個音可能在台灣越有人讀。
![image](https://user-images.githubusercontent.com/3164826/149626850-7f2475e2-9035-492d-8e2c-ab819bd8edd2.png)

**Comment by ShikiSuen** [comment]
其實「質」在台澎金馬唸陽平、陸規審音唸去聲，但以熱河為中心向全國輻射開來的近畿地區口音當中有超多人唸上聲(ˇ)。
我這邊考慮再三，在威注音當中收了這個字的上聲讀音(也就是ˊˇˋ三個調都收了)。

**Comment by zonble** [comment]
教育部改讀音被罵也不是第一次 https://udn.com/news/story/6898/5962831

**Comment by ShikiSuen** [comment]
@zonble MOE 的辭典在審音時，很多常見字的讀音莫名其妙地向陸規看齊。
正本清源與民間常用之間的取捨權衡很重要。
俄羅斯的俄、法國的法，都是唸去聲的，MOE 的規定都與之相左。
亞洲的亞也是，在台澎金馬民間唸雅、與齊鐵恨的老北京口音一致。
這些字太常用，這些讀音沒理由不收。

但 學 洨 同音 這個我真的是第一次聽說。

**Comment by ShikiSuen** [comment]
剛剛看了我手頭的 2010 年版「新編東方國語辭典」，裡面的「學」也只收了「ㄒㄩㄝˊ」這一個讀音。
可能季旭昇教授沒留意到有「洨」這個讀音吧，或者他可能是嫌棄有石楠花味道的讀音（誤）。
