### ISSUE TITLE
com.apple.keylayout.ZhuyinBopomofo 的相容性問題

### ISSUE THREAD

**Issue by ShikiSuen** [OpenVanilla/McBopomofo#200]
出於注音輸入教學演示的目的，我是希望能讓螢幕小鍵盤在開啟該輸入法時顯示注音的。
但我發現這必須得將所有「com.apple.keylayout.US」換成「com.apple.keylayout.ZhuyinBopomofo」。
但這樣一來這個輸入法反而無法正常工作了。
不知有沒有可以兩全的方法。

**Comment by zonble** [comment]
有些話想來是不太中聽，我也往往覺得不中聽的話也沒人會聽進去，不如不說也罷，但大概就藉著這張票一次說完好了。

在你開出這張票，直接伸手要一個解決方案之前，請問，你有沒有嘗試過自己找一下問題的原因呢？如果你連原因都不知道，那要怎麼找出技術方案呢？輸入法是個很冷僻的領域，有人願意投入，而不是去搞加密貨幣還是 NFT，基本上沒有不歡迎的道理，可是直接伸手要答案，就不是什麼會讓人高興的舉動。

簡單給個提示，macOS 在收到來自鍵盤的事件之後，會把事件封裝成 NSEvent 物件，然後我們可以從 characters 拿到系統把那個 key code 配對成哪些 character 與 modifier。改變了 keyboard layout，就會改變 key code 與 character 之間的對應，小麥注音輸入法所參考的是 character，而只有像處理方向鍵等功能鍵時處理 key code，那麼，如果收到預期之外的 character，輸入法引擎就不會處理。要怎樣知道到底收到什麼？在接收到 NSEvent 的地方，打一行 NSLog 就知道了。

如果你把 layout 設成 com.apple.keylayout.ZhuyinBopomofo，那麼可以發現，你打 Qwerty 的 1 會直接哪到 ㄅ，打 Q 會拿到 ㄆ，打 A 會拿到 ㄇ…目前幾個有開放出來的注音輸入法實作，大概都會預期接收到英文字母而非拿到注音符號，其中一項原因是，像小麥/Yahoo 用的 LibFormosa，還有酷音在用的 libchewing，都做了許氏鍵盤以及倚天二十六鍵排列，會把同一個英文字母視情況轉換成不同的注音符號。 

找到原因之後，就可以想出幾種方法。比方說，在收到系統傳來注音符號之後，我們再重新 map 回英文字母，送到只能夠接受英文字母輸入的輸入法引擎，這個可能最省事；或著，砍掉輸入法引擎的字母/注音符號轉換，以小麥來說，就得整個改寫 BopomofoReadingBuffer。但同時就得要注意大千鍵盤之外其他 layout 的取捨，因為必定會與其他鍵盤不相容。

一邊直接伸手要答案，你又經常強力推銷一些技術方案，就會讓人不舒服，原因是當中責任的不對等。你改了一個東西，做了一個技術選擇，但並沒有繼續負責探索下去，而要別人接收一套技術方案，最後有什麼問題是別人而不是你得負責。而推銷技術方案的理由又往往是你看過哪些網路資料，而不是你真的下去踩過雷，想評估會有什麼問題，花的是別人的時間。推銷技術方案這件事情背後很吃重信用的，如果無法展現出這種信用，給人的感受就是，你什麼都不用承擔，為什麼可以指手畫腳？

然後我會建議避免一些情緒勒索的用語。有的 Open Source 專案是大公司的策略，像微軟的 VSCode、蘋果做 Swift、Google 的 AOSP 或 Flutter，是用來打造他們平台的生態系用的，有些個人專案就只能苦苦支撐，完全不能確定什麼時候可以有時間弄一兩件 Open Source 的事情，我是大概上個月把幾個大案子忙完，過年前大部分只要做些  paper work，最近還有點時間做點事情。Open Source 的本質是分享，分享就該快快樂樂的，如果別人沒辦法讓你快樂，就只能自己想辦法。

既然是 Open Source，想 fork 想改寫都很自由，之前你講到「如果不做什麼功能我就得 fork 囉」、「如果還不改掉什麼東西我就得找技術援軍」這種「你不給糖吃我就不跟你好」的語氣實在沒有必要，講得好像別人沒時間或是還想不出來怎麼寫是多嚴重的罪過一樣，而且這種情緒勒索大概只有家人或可愛的女孩子才有用吧？沒必要散發這種負能量。

我之前瞄了一眼你的知乎，好像提到因為簡體中文圈對繁體用戶越來越不友善，所以非常需要一套可以合乎簡體中文環境的注音輸入法，而合規就是以官方為準。是否友善這種事情沒有什麼客觀材料，應該都只有主觀經驗吧？

我自己的工作中，每天上午要跟上海、成都各開十五分鐘的線上站立會議…然後後面可能會有一堆亂七八糟的會議，供應商在福州、深圳之類的地方，信件往來也往往簡繁交雜，我自己也被一些對岸的開發者加到了一些微信討論群裡頭，大抵來說，只要最後能讓雙方賺到錢，我不覺得寫繁體會造成我什麼麻煩，我在成都的主管還幫我晉升。我不知道你經歷了什麼，或是在什麼平台做了什麼發言，不過我建議，如果你覺得你在簡體中文圈不受歡迎，或許可以想想使用繁體字並不是唯一的原因。

如果別人是因為別的原因而不歡迎你，我也不覺得打造一套新的輸入法有什麼幫助，甚至可能引起反效果，像：「你明明就是台灣人，只拿了一些官方資料就想來教我什麼才是正確的簡體中文」之類的。

然後，說到去對岸推廣注音輸入法，我個人的經驗是，電腦上的中文輸入法已經出現三、四十年了，倉頡輸入法的年紀跟我一樣老，而這年頭的使用者幾乎都是小時候就開始學輸入法，對輸入法的要求上，有什麼新功能都算是其次，更重要的是習慣的延續，不管其他人眼中哪套新的輸入法更好，只要哪套符合原本的習慣，就用哪套。

輸入法就跟筷子一樣，亞洲人從小就學用筷子，我們覺得韓國人用的那種扁扁的鐵筷很難用，日本的筷子都很短很滑很難用，但是人家習慣養成了，也不會想用你覺得的更好的筷子。想要一個拼音用戶放棄拼音改用注音，就算裝了一套最好的簡體中文輸入法好了，在手機上、公共電腦上、公司配發不讓你自由安裝軟體的電腦上，他還是得打拼音，況且他可能已經打拼音幾十年了。以我作為一個工程師，我會選擇去尋找更具體急切的需求。

**Comment by ShikiSuen** [comment]
@zonble  這個 issue 我關晚了。
我承認有些情緒垃圾確實是我不該。

其實，只論回答這張票的話，客觀答案就是「沒有」這兩個字。參見我下文的觀點一。

最近一周以來看了很多東西，導致我很多想法都有改變。
整理了幾個我目前觀點，應該會在不同的角度和您有一些共同語言：

零、所謂情緒勒索，是我當初在輿論上試圖讓 Apple 換掉華文「黑體-簡/繁」（就是您之前寫 TCFail 的原因）的那些年養成的習慣性惡習。但我確實不該對開源專案這樣。

一、Apple 的 keyboardLayout 的侷限性決定了：要換注音鍵盤佈局的話，必須等同於再塞一個輸入法副本（instance）。雖然 Apple 成功將不同的注音鍵盤佈局塞到同一個 TCIM 當中，但這在 Xcode 裡面管理起來會小有難度（技術上可以實現，但是與小麥注音目前的架構風格應該會有很大差異）。另外一個就是：不只 Formosana 與 libChewing，連微軟新注音也是這樣處理的，直接證明 Apple 的做法是異類。今後有時間有技術條件的話，我可能會嘗試挑戰一下看看，但可能得對 Formosana 動手術。// Apple 對倚天佈局的擴充是在 TCIM 內建的某個模組當中的一個 XML 內定義的，或許可以拋磚引玉完成對許氏國音輸入法的佈局的支持。

二、關於我迄今為止在小麥注音倉庫提過的與讀音修正有關的內容，雖然我貼出的援引資料是我找來的，但我也有十年來在線上積攢的在台灣的人脈（主要是配樂相關的，其次是電玩粉絲）來幫我佐證一些讀音是否真的存在。有些讀音的取捨，我不只會查《現代漢語詞典》《重編國語辭典》《同音異讀表》，還都是要會問的、要問不同年齡階層的人。蚵仔煎、訐譙、囝仔、焢肉飯這些在台灣特別常用的台語詞的讀音，我都是在做過調查之後才確定下來的（當然這種詞不能收太多就是了）。

三、知乎這些年已經成為了一個火藥桶。你在參與某些討論的時候，稍微一不小心關掉了打繁出簡、或者急著用 iOS 內建的注音回覆了，立刻就會被對方定性為「屁股歪了（立場歪了）」。《BBS 鄉民的正義》裡面的鄉民的樣子，在知乎面前，都是小兒科。而且其實遠不只知乎，微博也是，很多著名的電玩的粉絲圈也都是。某知名電玩 IP 的上海後援會與廣州後援會各自有像黑社會一樣的高層因為嫉妒我的配樂才能（其實沒什麼才能，花了十年才摸到曾志豪的後腳跟而已，雙手拇指受傷練不了鋼琴，還有 ADHD 每天都要吃藥），就故意造謠說我「是台獨」「是行走的五十萬人民幣」。這會直接葬送我在大陸這邊今後的配樂生涯（我剛回國沒幾個月）、且會牽連我的家人，因為輿情一旦起來就沒有人聽你講道理。那個 IP 在大陸的所屬公司又管不了這些只知道吃裡扒外的後援會的作妖。我在威注音輸入法的關於視窗裡面寫說這個詞庫對某兩條法律做了合規處理，完全是為了自己保命（也是我的法定義務）。

四、然而我仍舊相信客觀真理的存在：我接觸大千並擊注音是 2011 年。當時是在知道大千注音的原理之後（這輸入特性非常馬克思）、逼著自己花了一個月的時間適應了盲打（都不需要注音貼紙）。之前是用智能狂拼系輸入法（包括後來的搜狗拼音）用到 2007 年秋天為止、換用微軟新注音 2007 的拼音模式（來追求繁體中文輸入的準確性）。國語中文圈總是有大多數人學不來字根輸入法的，而漢語拼音重碼率高、輸入節奏不穩、免不了很多場合要敲比大千注音更多的鍵。我盲打大千注音這十年來的經歷，使我得出結論：只有大千並擊注音才會在今後扮演電腦鍵盤音韻類普通話中文輸入的革命。這需要大概一二十年的時間來論證。唯一的障礙，在於學者是否願意集中一個月來學習適應、是否願意放下對注音與對台灣的偏見。畢竟，實事求是，就是馬克思主義追求的真理。

五、所以，基於上述三、四兩條，我認為世間必須要有一個能用的純簡體中文注音輸入法。微軟新注音 2010 的簡體中文模式是全球第一個純簡體中文注音輸入法，卻因為微軟以市佔率為由、堅持不修正「該模式敲不了略虐這兩個字」的 bug，而徹底成了廢物。OpenCC 無法從根本上解決正確率的問題，從化學元素用字就能看出來。至於小麥注音的原本詞庫，裡面被 MJHsieh 故意摻入的東西，在大陸這邊的網路上散播了就等於違法，所以我必須要在威注音內寫免責聲明。

六、關於技術推銷，我沒想到這一層。既然我不賺錢，那又何談銷售？但您講的也在理。給我的感覺就是：果然台灣與日本的社會一樣、比較強調人與人之間的界限感。我對這種氣氛確實非常苦手就是了。

（該貼文謝絕轉載。）

**Comment by zonble** [comment]
有個問題順便一併回答好了。在製作選字窗的時候，我覺得有兩件事情一定要掌握在自己的手裡，一是 Window Level，二是要能夠完全自己掌握視窗的擺放位置。如果 Window Level 沒設對，那麼選字窗可能會被前景的視窗蓋住，如果選字窗位置跑到螢幕之外，那麼用戶就看不到選字窗，而 IMKCandidate 到目前為止這兩者都沒開放出來。

Window Level 決定的是視窗之間的擺放位置，像浮動工具列要在一般視窗上面，選單又要比浮動工具列更上面，而選字窗必須要比這些東西更上面。目前小麥是設定成跟選單同層，就目前來看是夠用，但是過去有些應用程式會把自己設到比什麼都高，像是已經消失的 Front Row，還有就是一些全螢幕模式的遊戲。基本上如果又出現哪個超級人氣應用程式，但是又設了一個比其他人都高的 Window Level，我們大概就得出一個版本，把選字窗的 Window Level  設到更高。如果把這點交給蘋果，我們無法預期蘋果會不會針對某個應用程式修改 IMKit，然後 IMKit 的改版又是跟著 macOS 的週期推出，就算你有心有時間也修不了。

然後是選字窗的位置。選字窗的位置取決於應用程式先告訴作業系統，用戶是在程式中的哪個位置打字，作業系統再通知輸入法座標位置，IMKCandidate 提供的選項只有你想擺在用戶輸入位置的上下左右，你沒辦法直接指定視窗要位在螢幕（NSScreen）中的哪個位置上，那如果某個應用程式自己有 bug，告訴作業系統錯誤的座標位置，像以前魔獸世界流行的時候，魔獸世界就會給你一個 x 軸在大概一萬六千左右的詭異位置。如果能夠直接決定選字窗的位置，我們可以作起碼的修正，目前在小麥中只保留了這段：

https://github.com/openvanilla/McBopomofo/blob/master/Packages/CandidateUI/Sources/CandidateUI/CandidateController.swift#L109-L119

這段 code 的意思是，如果應用程式告訴你的選字窗擺放位置，根本不在任何一個 NSScreen 之內（用戶可能會有多個外接螢幕），我們還是會 fallback 回主螢幕，只少不會讓用戶看不到。而這樣的控制權我們不能交給蘋果。

**Comment by zonble** [comment]
我其實很感謝你對於詞庫的修正，不過你應該可以看得出來，我沒在管詞庫。 :p

然後為了清洗詞庫，一次 rebase 整個 git repo，要 PR 的 reviewer 一次看八百個 commit 裡頭有沒有出現什麼怪東西，我覺得應該沒有人有能力 review 這樣的 PR。

**Comment by ShikiSuen** [comment]
@zonble 所以那個pr我關了。XD

**Comment by zonble** [comment]
然後如果真的是糟忌的話，我覺得，不管你做什麼都很難改變，而且就算怎麼改變使用的語言，我不覺得一個人真正的出身是藏得住的。不過，我不熟悉你的行業，也沒辦法給什麼評論。

而順道一提，我覺得讓熟悉原本注音輸入法的人輸入簡中，與原本簡中文化圈中的人想用注音，兩者要用的詞庫可能會不一樣，主要出在有些字的兩岸讀音不同，像微笑的微台灣念二聲，對岸唸一聲，企業的企台灣念四聲，Wikipedia 上有分兩岸讀音差異表，但感覺起來應該也不全。

**Comment by ShikiSuen** [comment]
@zonble 威注音有針對這個做處理。只是需要時間。
目前優先解決台澎金馬當地 MOE 標準讀音（以重編國語辭典為準）與民間常用讀音的相容性問題（兩邊都作相容讀音），之後再以《現代漢語詞典》作為簡體中文陸規審音參考依據。

這樣多少會提升一些重碼率，但這方面的 debuff 不是很明顯就是了。
我從 2007 年開始逼著自己用世一辭典重新把國語學了一遍，早已習慣台澎金馬當地的審音。不然我用奇摩注音與微軟新注音應該很困難才對。

**Comment by ShikiSuen** [comment]
@zonble 順便問一下好了。請問您這次對小麥注音的集中研發大概會在什麼時候結束？
我們這邊完全跟不上小麥注音 upstream 的更新速度，也不知道您的研發計畫。
有些功能做了又不知道會不會變成無用功（比如針對 openCC 轉換的模式切換的提醒，之前 hiraku 做過一次 notification center 版的）。我這兩天一直在忙對 swift 版的 voltaire 選字窗的美化工作（之前的選字窗的審美還停在 Leopard 時代），很多之前花在 ObjC 熟悉的時間都要重新花一遍在 Swift 上。但我不知道這些是否有一天又會變成無用功。
