### ISSUE TITLE
在詞庫編譯用 makefile 當中將 LANG=C 換成 LC_COLLATE=C

### ISSUE THREAD

**Issue by ShikiSuen** [OpenVanilla/McBopomofo#201]
我不知道 MJHsieh 是否有過在兩台電腦之間來回輪換工作的情況。
我兩台 Mac 每次編譯之後 sort 的結果都不一樣。
將 LANG=zh_TW.UTF8 改成 LC_COLLATE=zh_TW.UTF8 之後，兩台電腦各自編譯時的 sort 排序結果終於一致了。
於是我猜想 McBopomofo 官方倉庫這邊是否有必要將 LANG=C 換成 LC_COLLATE=C。
畢竟，只調整 LANG 的話，不會對 sort 的結果有任何可控的影響。

**Comment by ShikiSuen** [comment]
訂正一樓內容為 LC_COLLATE。

**Comment by mjhsieh** [comment]
According to FreeBSD manual, we should use LC_COLLATE.  I did not have sorting problem with this project, however I brought my Linux habit anyway.   I appreciate the attention, but this makefile is not really user facing feature, so you should expect more slower response from this kind of issues.

**Comment by ShikiSuen** [comment]
@mjhsieh Thanks for your response.
Feel free to close this issue if you already addressed this.
