### ISSUE TITLE
想與 zonble 和 lukhnos 聊一下關於 swift 與 objC 的取捨問題。

### ISSUE THREAD

**Issue by ShikiSuen** [OpenVanilla/McBopomofo#214]
首先請教 @zonble 好了。
請問您將程式庫由 objC 轉成 swift 的原因是因為方便維護、還是因為 swift 相對於 objC 有什麼壓倒性的優勢嗎？
我昨晚 google 爬文發現 objC 在執行效率方面比 swift 快大約六倍：
https://bunn.dev/benchmark/2020/07/25/objc-vs-swift.html

然後就是我想知道 @lukhnos 是否贊成整個小麥注音專案全部 swift 化、還是說只是部分 swift 化。
畢竟很多牽涉到核心處理模組的內容都是 lukhnos 完成的。

------
P.S.: 該問題純屬好奇。至於威注音，目前會繼續 ObjC、對 High Sierra 保持相容性。
將來 cook.py 的部分會用 ObjC 重寫，徹底解除對 Python 的依賴。
也还可能擇日會將 SwiftyOpenCC 換用 ObjC 重寫。

**Comment by zonble** [comment]
C 與 C++ 語言有一大堆的 undefined behavior，像 Swift 這些現代語言首先要解決的就是 undefined behavior 的問題。在小麥注音上面，最重要的地方在於 Swift 有嚴格的形態檢查。

以小麥注音來說，在轉換成 Swift 之前，其實很多 API 的呼叫所傳遞的參數根本型態就是錯誤的，但是 ObjC compiler 並不能夠檢查出這些錯誤。比方說，在選字窗的地方，對 NSView 呼叫 setNeedDisplay 的時候，應該要傳入 NSRect 型態，表示這個 view 應該哪裡應該重繪，原本有很多地方卻寫成 setNeedDisplay:YES，傳入 BOOL 型態，這個 API 呼叫根本就寫錯了，在傳入錯誤的參數型態的時候，就可能出現無法預期的行為，很可能根本就不會重繪，程式會動就只是碰巧而已。

嚴格的形態檢查中，還有一項很重要的，就是對 nil 的檢查。同樣是選字窗 UI 的部份，很多邏輯其實在沒有指定 delegate 的狀況下，根本就不該繼續往下走。原本有些邏輯整個建立在 delegate 不會 assign 到 nil 的假設上，但是寫 code 不太應該這樣寫，雖然每塊磚頭都是歪的，堆出來的房子還是可以住，但是你想稍微動一下哪塊磚頭，這種房子就很容易就垮了。

我覺得小麥基本上大概有兩個地方特別需要效能，第一個是 FastLM 載入 data.txt 的 parser 的部份，另外一個則是 Walker 裡頭的那段演算法，其餘地方，都是正確性遠高於效能。以選字窗這種 UI 來說好了，輸入法的選字窗又不像遊戲畫面需要一秒鐘更新 60 次，但是 ObjC 的型態一搞錯就是沒事就會 crash 的。用 C++ 寫的引擎是小麥的核心，不過應該得要再封裝一層。

這些年蘋果的新的 API 都慢慢只有 Swift 版本了，先不說 SwiftUI，像是 Combine 與 SwiftCrypto，都只有 Swift 的版本，如果想使用一些比較先進的蘋果技術，那麼就不可能停留在純 ObjC 的世界了。Swift 這幾年另外一個重點在於 concurrency，不過這對小麥影響還好，小麥畢竟不是那種同時兼有幾十條網路連線的哪種 app。

我的你的專案沒有任何評論。

**Comment by ShikiSuen** [comment]
@zonble 感謝您的講解。
