### ISSUE TITLE
台澎金馬方言錯誤字詞自動轉換

### ISSUE THREAD

**Issue by ShikiSuen** [OpenVanilla/McBopomofo#231]
我記得之前奇摩注音有這個自動更換的功能的，會把懶趴自動改成卵苞（其實是卵脬）。

近期 @zonble 做出了相關的功能，所以小麥注音或許可以考慮將雅虎奇摩注音的這個功能繼承過來。

相當一批詞的出處：https://www.facebook.com/remy.gils/posts/493027495511954

這是我整理的清單：

歸剛 規工
母湯 毋通
好康 好空
凍未條 擋袂牢
凍蒜 當選
阿兜仔 阿啄仔
逗陣 鬥陣
甲意 佮意
吐槽 黜臭
底加 佇遮
趴趴走 拋拋走
巴豆妖 腹肚枵
婚逃 薰頭
賣卵蛋 莫亂擲
歐北共 烏白講
水噹噹 媠噹噹
安抓 按怎 
拍謝 歹勢
呷洨 食潲
呷飽 食飽
尚好 上好
氣噗噗 氣怫怫
洽北北 刺耙耙
甘安 敢按
七逃 𨑨迌
歹丸 台灣
乎乾 予焦
訐譙 姦撟
幹譙 姦撟
蝦咪 啥物
三小 啥潲
啥洨 啥潲
靠腰 哭枵
懶趴 𡳞脬 // 蘋方不支援「𡳞」字，恐需暫時用「卵」。
雞掰 膣屄
靠北 哭爸

以下詞彙因為容易與國語常用字詞混淆，所以需要單獨加詞（台澎金馬方言讀音 cc @mjhsieh  ）：

𡳞鳥&卵鳥 // 蘋方不支援「𡳞」字，恐需暫時用「卵」。
現挽
豐沛

// 我自己的詞庫會直接收這些詞，但不見得會是最優先等級。有些錯誤寫法已經深入人心，強行斧正反而會帶來不適應。

**Comment by zonble** [comment]
這個用自訂的詞彙轉換來做應該就夠了，讓有需要的用戶自己轉換吧。
