### ISSUE TITLE
[功能建議][防呆設計] 選字鍵定義選項需要增加檢測重複數值的功能

### ISSUE THREAD

**Issue by ShikiSuen** [OpenVanilla/McBopomofo#234]
**痛點**
有時有人在輸入這個數值的時候會好死不死地遇到鍵盤出問題的情況，特別是敲一下按鍵結果被系統當成敲兩次。
這時錯誤的數值（比如 114514191）就會被輸入進去。
當這種情況出現的時候，voltaire 對同一個選字鍵的多筆字詞，僅能輸入優先權最高的那個。

**功能改進說明**
在偏好設定視窗的 controller 當中，針對這個輸入框的數值做出這種處理：
使用者輸入數值之後，先過一個新函數來濾除所有重複內容，然後再轉回到目前現有的「判斷長度是否等於 9」這個判斷過程來。

**Comment by ShikiSuen** [comment]
我給出我的解決方法：
在 PreferencesWindowController 當中：

```
import Cocoa
import Carbon
```
這兩行之後插入：
```swift
// Extend the RangeReplaceableCollection to allow it clean duplicated characters.
extension RangeReplaceableCollection where Element: Hashable {
    var charDeDuplicate: Self {
        var set = Set<Element>()
        return filter{ set.insert($0).inserted }
    }
}
```

之後檢索
```swift
    @IBAction func changeSelectionKeyAction(_ sender: Any) {
```
將之後的這行：
```swift
let keys = (sender as AnyObject).stringValue.trimmingCharacters(in: CharacterSet.whitespacesAndNewlines)
```
換成這行（就是在行尾追加`.charDeDuplicate`）：
```swift
let keys = (sender as AnyObject).stringValue.trimmingCharacters(in: CharacterSet.whitespacesAndNewlines).charDeDuplicate
```
實測有效。抄送 @zonble 

回頭套用這個修正時不要把我寫在 coauthor 當中。

---

Fixed a bug to ensure that the customized candidate keys will always consist of unique characters. Entries like "1145141919" will be recognized as "1459" prior to the validity check process.

**Comment by zonble** [comment]
PR #236 修正。

後來的作法是直接在 model 層寫一個 validator，如果格式錯誤，就直接顯示錯誤提示。
