### ISSUE TITLE
[功能問題回報] 輸入時緩衝區最多只能保持十個中文字的選字狀態

### ISSUE THREAD

**Issue by heyaojung** [OpenVanilla/McBopomofo#255]
在您回報問題之前，建議也可以先參考 Wiki 上的 [常見問題](https://github.com/openvanilla/McBopomofo/wiki/%E5%B8%B8%E8%A6%8B%E5%95%8F%E9%A1%8C) 與 [使用手冊](https://github.com/openvanilla/McBopomofo/wiki/%E4%BD%BF%E7%94%A8%E6%89%8B%E5%86%8A)

**摘要**
請簡單說明您遇到了什麼問題。這份表格雖然是中文的（我們相信注音輸入法的用戶應該都能看懂中文），但開發團隊可以使用中英文溝通，您也可以使用英文回報問題。

**快速分類**
請問您遇到的是：
- [x] 其他：輸入時緩衝區最多只能保持十個中文字的選字狀態

**問題發生步驟**
1. 打開任何可以輸入中文字的程式
2. 開始在輸入區域打字
3. 一次輸入超過10個中文字，從第11個字開始，第1個字會從緩衝區移除變成已選定的字，以此類推....
4. 例如：一二三四五六七八九十壹，輸入到「壹」後，「一」這個字就沒辦法再進行選字

**預期正常狀況**
您覺得這是不正常的狀況，那您覺得正常結果應該是…？
正常應該是不限字數的讓使用者把所有中文打完之後再回過頭來選字確認

**電腦環境**
請問您在怎樣的環境遇到這個問題？

- 小麥注音版本：2.01
- 鍵盤樣式：
  - [x] 標準

- macOS 版本：12.1
- 在哪個應用程式中打字遇到問題：（microsoft edge、 Teams 等所有可以輸入中文字的程式）
- 電腦機種：Macbook Pro 13 2019 Intel Chip
- 其他特殊設備：無
- 特殊設定：安裝使用後就發現了此問題
**其他**
希望可以放寬這個選字字數的限制，謝謝。

**Comment by ShikiSuen** [comment]
這個上限是必需的，但不一定非得是十個字。
而且，這個上限越高，對電腦效能要求也越高。
當初小麥注音設這個上限，是考慮到 PowerMac 的效能限制。

請問您希望這個緩衝區最多能塞多少字？

**Comment by ShikiSuen** [comment]
另外「正常應該是不限字數的讓使用者把所有中文打完之後再回過頭來選字確認」……
根據我這十年來對並擊型智慧注音輸入法的使用體驗（微軟新注音 2007-2010-至今，奇摩輸入法用了八年），
比較穩妥的作法還有一種，就是：**用 Enter 將正確的內容敲一點送出一點、送出一點是一點，緩衝區不要攢太多內容**。
那些罵微軟新注音選字爛的，都是喜歡往緩衝區攢太多內容的。我下文馬上就講原因。

能做到智能選字的輸入法，都會內建一個八股文系統（小麥注音的話，就是 phrase.occ，新酷音的話，就是 tsi.src 裡面的頻率數據）。考慮到智能並擊注音的輸入特性，如果是要支撐您所需要的超過十個字的緩衝區、且還要保證準確率的話，那麼八股文內也需要相當詞長的正確的組句數據才對。這會讓八股文系統的體積變得不堪重荷。

小麥注音輸入法目前尚未引入 SQLite，而 SQLite 商業版一套的價錢真的很要命（卻又有非常重要的壓縮功能）。
所以小麥注音輸入法目前還是在用 csv 格式，只不過以 txt 作為副檔名、以空格作為分隔符罷了。
缺點就是會很肥。在此基礎上讓八股文滿足超過十個字的緩衝區的需求的話，可能得更肥才行。

以上是我的拙見。

**Comment by heyaojung** [comment]
感謝您的說明，對於限制的原因我已了解，如果可以的話，我希望可以放寬到20個字，因為以我個人而言10個字真的很容易超過XD....
再次感謝您聽取我的建議以及回覆，謝謝！

Shiki Suen ***@***.***> 於 2022年1月24日 週一 下午5:52寫道：

**Comment by lukhnos** [comment]
使用者可以自行更改組字區字數: https://github.com/openvanilla/McBopomofo/wiki/使用說明_其他可以透過終端機調整的進階設定
