### ISSUE TITLE
[WIKI 錯誤回報] 請訂正對微軟新注音輸入法 Win11 的描述

### ISSUE THREAD

**Issue by ShikiSuen** [OpenVanilla/McBopomofo#256]
https://github.com/openvanilla/McBopomofo/wiki/行為比較

### 一、微軟新注音自 2007 版開始便已經可以用 SHIFT+ 方向鍵來自訂語彙：

<img width="437" alt="截圖 2022-01-19 20 11 41" src="https://user-images.githubusercontent.com/3164826/150680712-46095c6d-b251-45e3-961f-81bda457d0f4.png">
且我剛剛用 WIN11 測試發現該功能仍舊存在：
<img width="596" alt="image" src="https://user-images.githubusercontent.com/3164826/150680741-c24bee9b-3279-4655-9460-4eebd442aa36.png">

### 二、微軟新注音沒有繁簡轉換，而是簡繁體模式的語料庫各自獨立。

（微軟是全球第一家、威注音是全球第二家這樣做的。）

稍微試用一下就可以發現：

1. 略 虐 這兩個字音在簡體模式下敲不出來。這個 bug 從微軟新注音 2007 開始至今都沒被修復。我在微軟有朋友幫忙詢問相關部門，得到的答覆是說因為該功能的市佔率的原因而故意不修（除非 insider feedback hub 有超多人提出修復請求才會響應）。
2. 這個模式的漢字讀音僅支援陸規審音。無論是台澎金馬民間習慣的讀音、還是 MOE 規範讀音都不支援。
3. 很多詞彙的末尾字僅支援輕聲。

至於該 wiki 頁面對微軟新注音的其它表述，我沒有測試驗證，就煩請主筆者自己測試一下了。

**Comment by ShikiSuen** [comment]
P.S.: 我打鬥陣時就是仰仗微軟新注音輸入法的 SHIFT 加詞功能，不然諸如法雞路西歐花村半藏源氏等詞沒辦法瞬間敲出來。
印象中能與鬥陣的聊天視窗完美整合的輸入法好像並不多。

**Comment by ShikiSuen** [comment]
P.P.S.: Issue Template 再新增一個與 wiki 有關的範本好了。

**Comment by zonble** [comment]
Fixed.

**Comment by ShikiSuen** [comment]
@zonble 在這邊問一下好了。請問 Shift 方向鍵加詞的功能是您趁 Space Chewing 發明的嗎？
