### ISSUE TITLE
[功能建議]半形標點符號快捷鍵切換

### ISSUE THREAD

**Issue by pakerchang** [OpenVanilla/McBopomofo#257]
Hi, 機緣巧合下碰到才知道小麥注音，一試就愛上

因為沒有找到修改中文模式符號鍵位設定的地方
我碰到的問題如下： ` " " `符號中的同鍵位在全形和半形、英文對應的符號並不相同
希望可以和簡體中文功能一樣設置快捷鍵快速切換，有試過利用`、`搭配半形符號設定來替代全形符號的輸入需求
奈何手太殘一直適應不良

如果已有對應的解決方式，希望能指引我傳送門

謝謝 <(__ ^ __)>

**Comment by zonble** [comment]
請教一下，您想要的是快速輸入半型空白嗎？目前的作法是，在還在輸入中文的時候，先按 Enter 把中文送出，接下來直接按空白，就會送出半型空白了。

**Comment by pakerchang** [comment]
忘了附圖抱歉
原本是指全形模式下`""` `、` 符號在鍵盤上的鍵位與半形模式不同，但找不到可以自行更改鍵盤上符號鍵位的地方，使用習慣上，用了一陣子都是在半形模式下配合`~`鍵叫出選單來搭配使用，因為手勢衝突一直不適應才跑來問
但回覆這篇文章的時候才意識到，可以`caps lock` 切換到英文輸入就能避免

謝謝你的幫忙，我想我應該找到解決方式了，就是有點蠢XD

<img width="218" alt="截圖 2022-01-26 上午1 50 42" src="https://user-images.githubusercontent.com/8652935/151031837-699167f1-3e5d-4b10-a5c2-40686d764b2c.png">

**Comment by zonble** [comment]
Hi,

還是想跟您確認一下，請問您是覺得現在輸入「、」不方便，還是輸入「"」以及「'」不方便呢？

目前在智慧選字的注音輸入法中，使用「'」來對應到頓號「、」，這主要是來自於自然與酷音輸入法的習慣，這點應該對於同時還需要使用 Windows 以及 Linux 的用戶來說，在跨平台時可以維持一樣的習慣。我先假設您之前長時間使用 Mac 內建的注音輸入法，或是更早之前的漢音輸入法用戶，由於這些輸入法將頓號對應到「＼」上，「'"」這兩個按鍵還是輸出半型標點。

如果是這樣的話，小麥現在可以透過加詞表格以及刪詞表格，達到這樣的行為。在輸入法選單中，有兩個功能「使用者詞彙」與「排除的詞彙」，就是加詞與刪詞表格，然後按照以下內容輸入

https://github.com/openvanilla/McBopomofo/wiki/%E4%BD%BF%E7%94%A8%E8%AA%AA%E6%98%8E_%E6%BC%A2%E9%9F%B3%E9%A2%A8%E6%A0%BC%E6%A8%99%E9%BB%9E%E7%AC%A6%E8%99%9F

修改完畢、存檔後，選一下「重新載入使用者詞彙」。

另外，如果要快速輸入 " 與 ' ，其實可以按著 Ctrl 之後按下這兩個按鍵。

**Comment by zonble** [comment]
我們在最近的程式更改中，也加上了一個切換全半型符號的快速鍵。

**Comment by pakerchang** [comment]
感謝您的幫忙！
很抱歉我的描述能力太糟，把問題弄的複雜化
的確用 Mac 內建輸入法很長一段時間，左手因為打字移動幅度太大的話容易抽筋，所以鍵盤左上角是冷區很不適應QQ

也期待接下來新的快捷建。

謝謝

**Comment by zonble** [comment]
先關閉這張 issue :)
