### ISSUE TITLE
[功能問題回報] 小麥在 Messenger App 桌面版輸入會中斷

### ISSUE THREAD

**Issue by chanyuding** [OpenVanilla/McBopomofo#258]
**摘要**
在桌面版的 Facebook Messenger app 輸入文字時，只要文字超過一定長度就會自動消失

**快速分類**
請問您遇到的是：
- [x] 其他

**問題發生步驟**
請問您是怎麼遇到這個問題的？像是：

在桌面版的 Messenger app 輸入文字時，只要文字超過一定長度就會自動消失

**螢幕截圖或螢幕錄製**
https://user-images.githubusercontent.com/6885942/151290456-c3b8c19c-b95e-4b8e-8f32-2a23aac95a4d.mov

**電腦環境**

- 小麥注音版本：2.0.1 (1058)
- 鍵盤樣式：
  - [x] 標準

- macOS 版本：Big Sur
- 在哪個應用程式中打字遇到問題：Facebook Messenger App / 版本 134.0
- 電腦機種：M1 Macbook Air 2020
- 其他特殊設備：無
- 特殊設定：無

**其他**
感謝小麥開發者的辛勞，真的是很棒的輸入法！

**Comment by lukhnos** [comment]
我用 Messenger 137.1 (347181832) 無法重現這個問題，是否可以安裝新版試試看？

倒是我注意到 Messenger 137.1 在組字區仍有字時，切換輸入法或切換應用程式，可能會造成組字區不會被完全清乾淨的問題，但這問題在使用內建的注音輸入法時也會發生。看來是 Messenger 對輸入法支援有一些 edge conditions 沒處理好。

**Comment by chanyuding** [comment]
更新至 版本137.1（347181832）後解決以上問題，非常謝謝！

**Comment by lukhnos** [comment]
> 更新至 版本137.1（347181832）後解決以上問題，非常謝謝！

謝謝你確認！
