### ISSUE TITLE
[功能問題回報] PgUp / PgDn 不但不出現選字窗，反而會輸入「ㄝ/ㄜ」。

### ISSUE THREAD

**Issue by ghost** [OpenVanilla/McBopomofo#267]
**摘要**
這篇其實算是包含兩部分吧。
希望「摁 PgUp / PgDn 出現選字窗」是功能建議；
「摁 PgUp / PgDn 反而會輸入「ㄝ/ㄜ」」是問題提報。

**快速分類**
請問您遇到的是：

- [x] 其他

**問題發生步驟**
試圖使用 space 或者向下方向鍵（縱排輸入時則是向左方向鍵）叫出選字窗時，如果想改用 pgUp / pgDn 叫出的話，就會這樣。

**預期正常狀況**
在沒有計畫做 pgUp / pgDn 叫出選字窗的功能的情況下，希望能至少阻止其輸入「ㄝ/ㄜ」。

**螢幕截圖或螢幕錄製**
不需要。

**電腦環境**
請問您在怎樣的環境遇到這個問題？

- 小麥注音版本：2.0.1
- 鍵盤樣式：
  - [x] 標準
- macOS 版本：macOS Monterey 12.2
- 在哪個應用程式中打字遇到問題：無論任何程式
- 電腦機種：Mac mini (M1)。
- 其他特殊設備：ThinkPad 末代七列 USB 鍵盤（SK-8855）。
- 特殊設定：對 Mac 原生鍵盤的使用者而言可能毫無影響，畢竟對 Apple 筆電鍵盤而言 PgUp / PgDn 是需要摁 Fn 的，比較麻煩。

**其他**
ThinkPad 末代七列 USB 鍵盤超經典，敲字舒適感真的很棒。

**Comment by zonble** [comment]
Fixed in #268.
