### ISSUE TITLE
[功能建議][轉載意見] SpaceChewing 與新酷音那樣的符號表

### ISSUE THREAD

**Issue by ShikiSuen** [OpenVanilla/McBopomofo#277]
**Disclaimer**
This issue is only a notification telling the repo hosts what is happening with the product built by the source code provided in this repo and shalt not be discrimitively & explicitly abused like "being regarded as a blackmail". To avoid being misunderstood: NO ONE IS RESPONSIBLE FOR DEALING WITH THIS ISSUE.

該功能提議非本人所求（我用不到，不會因為這份工單而受益），
只是在 Mobile01 看到有前香草酷音輸入法用家想繼續用這款功能，所以我就把工單開在這邊、誰樂意做誰去做。

## **痛點**
有上了年紀的前香草輸入法（特別是香草酷音輸入法）的使用者跟我說**他希望能用到所謂「香草波浪鍵符號輸入」的功能**。
https://www.mobile01.com/topicdetail.php?f=482&t=6533809
我請他給出具體的規範，他就擷圖給我看。我一看就發現那是新酷音 TSF 的功能：
（系統是 Windows 7 x64；該功能摁波浪鍵觸發時無須摁 SHIFT 鍵。
至於之前香草酷音輸入法是否持有雷同的操作方法，我不清楚、也無法搞到老電腦做實際測驗，估計香草酷音的製作人比我懂。）
![image](https://user-images.githubusercontent.com/3164826/152480580-9dfa6a72-25f4-4e23-8e25-c03994271a91.png)
![image](https://user-images.githubusercontent.com/3164826/152480622-d1ffbde0-45fc-4b71-bd1f-c6e648e07bb4.png)

我估算了一下之後，發現以我目前的能力並不能允許我做出這種二級選單功能。

## **功能說明**
以下是我對新酷音 TSF 的雷同功能的理解。
**如果香草酷音輸入法的功能與我的描述有出入的話，以香草酷音為準**。

在不摁住 shift 的前提下敲波浪鍵時，會叫出第一級選單（參見上圖一）。
一級選單是分多頁的，取決於上圖二那樣的符號表格內有多少行。
任選其一之後，進入對應的二級選單。
二級選單內的候選字（符號）數量取決於上圖二每一行內定義的子符號的數量。
（可能需要寫一個針對 symbols.dat 的 parser、再與 keyhandler 做結合吧。）

考慮到新酷音採 3x3 九宮矩陣顯示，恐怕 voltaire 選字窗需要做出對應的改動、才能還原相同的體驗。
我不知道香草酷音是否也有 3x3 九宮矩陣選字窗就是了。

**替代方案**
替代方案就是自己去改 data.txt。然而這樣做不出二級選單功能。

**Comment by zonble** [comment]
我寫一個多層的符號表範例給你。先簡單 hardcode 就是了。

https://github.com/zonble/McBopomofo/commit/5cb6819e132a02bbcba77dbf083ada418750dab7

真的需要格狀選字窗的話，拿現在的橫向選字窗改一下就有了。



https://user-images.githubusercontent.com/53011/152539647-7cb22f02-e4da-4370-bed5-b3ef8ad7b513.mov
