### ISSUE TITLE
忘記更新 updates/Info.plist

### ISSUE THREAD

**Issue by Hokila** [OpenVanilla/McBopomofo#281]
更新版本時會去抓 https://mcbopomofo.openvanilla.org/updates/Info.plist

並且比對 local 版號需不需要更新，

發現線上的 plist 內容版本是 0.99，但是事實上 release note 已經出到 2.0.1 了

下圖，左邊是我剛剛抓的 updates/Info.plist，右邊是 local master branch 的

![CleanShot 2022-02-09 at 15 30 10](https://user-images.githubusercontent.com/1647434/153142452-cd1c77a9-70dd-4ff9-a08a-077692831de9.png)

**Comment by lukhnos** [comment]
確實很久沒有發布自動更新資訊。我們得考慮是否有 0.9.9 的使用者已經無法升級上去（例如 macOS 10.10 之前的版本）。這個會需要一些時間從 update endpoint 下手。

**Comment by Hokila** [comment]
了解，那我關掉了，期待某日更新

**Comment by lukhnos** [comment]
這件事進行了很久，總算有進展。趁 2.9.0 版發布，一併更新了伺服器上的版本更新資訊。我們也採取分批方式發布，這樣用戶看過一次版本更新通知，隔一陣子後才會再次看到提醒。

手動檢查的話，自 2.5 版開始，就總是會看到最新的版本資訊了。
