### ISSUE TITLE
[功能問題回報] 在小麥注音模式下，按著 shift 不再直接輸出大寫英文字，而是進入英文選字狀態

### ISSUE THREAD

**Issue by wildjcrt** [OpenVanilla/McBopomofo#292]
在您回報問題之前，建議也可以先參考 Wiki 上的 [常見問題](https://github.com/openvanilla/McBopomofo/wiki/%E5%B8%B8%E8%A6%8B%E5%95%8F%E9%A1%8C) 與 [使用手冊](https://github.com/openvanilla/McBopomofo/wiki/%E4%BD%BF%E7%94%A8%E6%89%8B%E5%86%8A)

**摘要**
我使用的是「小麥注音」而非傳統注音。
在注音模式下，以往習慣會按著 shift 來直接打出大寫英文字，在 2.0 都還是這樣，升上 2.2 後行為變成英文選字狀態，且預設小寫。
我有錄影，希望可以比較清楚的理解需求。

**快速分類**
請問您遇到的是：

- [ ] 當機或應用程式閃退
- [ ] 輸入法叫不出來，或無法正確輸出中文
- [v] 無法切換到特定功能
- [ ] 輸入法效能有問題（執行速度太慢/電腦發燙）
- [ ] UI 顯示不正常
- [ ] 其他

**問題發生步驟**
請問您是怎麼遇到這個問題的？像是：

1. 隨便進到一個輸入框，像是 chrome 的網址列
2. 切換到注音模式開始打字
3. 需要輸入英文字時，按著 shift 打字即可重現，像是輸入 mac （參考錄影）

**預期正常狀況**
希望可以設定，是否開啟這種英文選字狀態。
預期要能夠直接在注音模式下快速大出大寫英文。

**螢幕截圖或螢幕錄製**
![bopomofo](https://user-images.githubusercontent.com/175151/154193596-c2911247-7a3a-4f0f-ac84-dd8e6221734c.gif)

**電腦環境**
請問您在怎樣的環境遇到這個問題？ 

- 小麥注音版本：2.2.1
- 鍵盤樣式：
  - [x] 標準
  - [ ] 倚天
  - [ ] 許氏
  - [ ] 倚天 26 鍵
  - [ ] 漢語拼音
  - [ ] IBM
- macOS 版本：12.0.1
- 在哪個應用程式中打字遇到問題：任何輸入框都會
- 電腦機種：MBP 13" M1, 2020
- 其他特殊設備：無
- 特殊設定：無

**其他**
2.0 => 2.2 後的行為變動

**Comment by lukhnos** [comment]
發布了 2.2.2，把 #293 的程式碼整合進去: https://github.com/openvanilla/McBopomofo/releases/tag/2.2.2

**Comment by wildjcrt** [comment]
安裝 2.2.2 後，確認行為恢復了，感謝！
