### ISSUE TITLE
Shift + 英文字母，行為隨組字區是否有字有所不同

### ISSUE THREAD

**Issue by lukhnos** [OpenVanilla/McBopomofo#295]
在討論 #293 (相關還有 #237 與 #162) 的時候，我們發現 Shift + 拉丁字母的行為，會隨組字區是否有字而有不同：

* 不在組字狀態時，按 `Shift + [A-Z]` 的行為是出大寫拉丁字母。傳統注音模式也是這樣。
* 組字區已經有字時，按 `Shift + [A-Z]` 的行為是預設出小寫拉丁字母，然後每個字都可以透過選字變為半形大寫、全形小寫，或全形大寫。

**Comment by zonble** [comment]
這個修掉了，先關 :)
