### ISSUE TITLE
[功能問題回報] 沒有自動選字

### ISSUE THREAD

**Issue by xareelee** [OpenVanilla/McBopomofo#300]
**摘要**

沒有自動選字與重複輸入權重。當我輸入以下字彙時，會出現非預選結果 (非清單上排序第一的結果)

- 自會 -> 期望: 字彙
- 育選 -> 期望: 預選
- 音此 -> 期望: 因此
- 一就 -> 期望: 依舊
- 地衣個 -> 期望: 第一個
- 也救市 -> 期望: 也就是
- 將美件事 -> 期望: 將每件事

以上的案例，進入選字清單時，第一選項都是出現期望的的結果，但小麥輸入法沒有自動幫我選取。
另外，重複手動選取該字彙後，下次輸入依舊出現非預選結果。變成每次輸入都需要手動選取。
我發現如果我再打下一個字，則前面的字彙才「有可能」幫我選取 (也就是並非每次都會自動選)。

**快速分類**
請問您遇到的是：

- [x] 其他

**問題發生步驟**
就正常打字，但是一直沒有學習選字功能。

**電腦環境**

- 小麥注音版本：2.2.1 (1202)
- 鍵盤樣式：
  - [x] 標準
- macOS 版本：macOS 12.2.1
- 在哪個應用程式中打字遇到問題：所有 App
- 電腦機種：MacBook M1 Max 2021（Apple Silicon CPU）
- 其他特殊設備：built-in keyboard
- 特殊設定：安裝後就如此

**Comment by Kent-Liu** [comment]
我也有完全一樣的問題。

- 小麥注音版本：2.2.1 (1202)
- 鍵盤樣式：倚天
- macOS 版本：macOS 12.2.1
- 在哪個應用程式中打字遇到問題：所有 App
- 電腦機種：MacBook M1 Max 2021（Apple Silicon CPU）
- 其他特殊設備：built-in keyboard
- 特殊設定：安裝後就如此

**Comment by lukhnos** [comment]
兩位都碰到了小麥選字資料與簡單語言模型的侷限。「自」跟「會」都是出現頻率高的單字詞 ，於是在簡單模型中，「字彙」無法比過「自」與「會」同時出現的情況：

```
ㄗˋ 自 -2.75449170
ㄏㄨㄟˋ 會 -2.42482529
ㄗˋ-ㄏㄨㄟˋ 字彙 -5.86869896
```

於是

```
P(字彙) =  -5.86869896 < P(會|自) ~= P(自)P(會) = -2.75449170 + -2.42482529 (log prob.) = -5.17931699
```

「一就」的情況類同。

我打「ㄉㄧˋ ㄧ ㄍㄜ˙」無法重現「第一個」總出現「地衣個」的問題。

我也無法重現「因此」、「也就是」跟「將每件事」的狀況。

治標的辦法是手工提高「字彙」等詞的分數。

> 另外，重複手動選取該字彙後，下次輸入依舊出現非預選結果。變成每次輸入都需要手動選取。
> 我發現如果我再打下一個字，則前面的字彙才「有可能」幫我選取 (也就是並非每次都會自動選)。

看來是用戶選字記憶機制 (user override model) 在這情況下沒有發揮作用。所以補強該機制也是個解法。
