### ISSUE TITLE
[功能問題回報] 漢音風格游標判定方面可能需要調整的地方

### ISSUE THREAD

**Issue by ghost** [OpenVanilla/McBopomofo#304]
鍵盤問題導致該 issue 被重複張貼。這個先關掉。
一切以 https://github.com/openvanilla/McBopomofo/issues/305 為準。

**Comment by LongJohn-Teabag** [comment]
鍵盤問題導致該 issue 被重複張貼。這個先關掉。
一切以 #305 為準。
