### ISSUE TITLE
性能問題

### ISSUE THREAD

**Issue by xareelee** [OpenVanilla/McBopomofo#307]
**摘要**

1. 快速輸入符號時，會有非常明顯的卡頓問題；在 Chrome 瀏覽器、內建 TextEdit；包括現在正在提交此 issue 的輸入框也是發生卡頓。
2. 在 Chrome 瀏覽器利用 `cmd + w` 關閉視窗時，也發生卡頓 (切換到使用系統英文輸入就不會有卡頓)。

卡頓說明:

1. 輸入一串文字時，UI 更新顯示輸入的狀態非常慢，常常打完五個字，介面才顯示 3 個字。
2. 任何 keystroke 的響應時間都非常慢，包括倒退鍵刪除文字、一些熱鍵。

**快速分類**
請問您遇到的是：

- [x] 其他

**問題發生步驟**
如摘要所述

**電腦環境**

- 小麥注音版本：2.2.1 (1202)
- 鍵盤樣式：
  - [x] 標準
- macOS 版本：macOS 12.3
- 在哪個應用程式中打字遇到問題：所有 App
- 電腦機種：MacBook M1 Max 2021（Apple Silicon CPU）
- 其他特殊設備：built-in keyboard
- 特殊設定：安裝後就如此

**Comment by lukhnos** [comment]
請問是否有任何檔案夾（例如 `~/Library/Application Support/` 或是 `~/Library/Input Methods/` 等等）是網路磁碟，或是否有任何小麥的資料檔是透過 symlink 指向其他地方？

又，Activity Monitor 顯示的小麥 CPU 用量是多少呢？

如果降級回小麥 1.1 還有這樣的問題嗎？

**Comment by xareelee** [comment]
以上問題在重開機之後就解決了，我再關注看看。因為當時使用 macOS 系統的注音似乎也是一樣。不確定是不是之前操作或安裝什麼軟體導致。
