### ISSUE TITLE
[功能問題回報] 使用自訂終端機輸入修改緩衝區長度失敗

### ISSUE THREAD

**Issue by Nighteye841228** [OpenVanilla/McBopomofo#308]
在您回報問題之前，建議也可以先參考 Wiki 上的 [常見問題](https://github.com/openvanilla/McBopomofo/wiki/%E5%B8%B8%E8%A6%8B%E5%95%8F%E9%A1%8C) 與 [使用手冊](https://github.com/openvanilla/McBopomofo/wiki/%E4%BD%BF%E7%94%A8%E6%89%8B%E5%86%8A)

**摘要**
請簡單說明您遇到了什麼問題。這份表格雖然是中文的（我們相信注音輸入法的用戶應該都能看懂中文），但開發團隊可以使用中英文溝通，您也可以使用英文回報問題。

**快速分類**
請問您遇到的是：

- [ ] 當機或應用程式閃退
- [ ] 輸入法叫不出來，或無法正確輸出中文
- [ ] 無法切換到特定功能
- [ ] 輸入法效能有問題（執行速度太慢/電腦發燙）
- [ ] UI 顯示不正常
- [x] 其他

**問題發生步驟**
請問您是怎麼遇到這個問題的？像是：

1. 打開terminal
2. 輸入 `defaults write org.openvanilla.inputmethod.McBopomofo ComposingBufferSize -int 1500`
3. 之後選字區長度依然只有20個字

**預期正常狀況**
您覺得這是不正常的狀況，那您覺得正常結果應該是…？

**螢幕截圖或螢幕錄製**
https://user-images.githubusercontent.com/14344978/161044459-605b8f34-3a73-4fbf-9039-8352d99207f2.mov

**電腦環境**

- 小麥注音版本：2.2.2
- 鍵盤樣式：
  - [x] 標準
  - [ ] 倚天
  - [ ] 許氏
  - [ ] 倚天 26 鍵
  - [ ] 漢語拼音
  - [ ] IBM
- macOS 版本：Monterey 12.3
- 在哪個應用程式中打字遇到問題：都有
- 電腦機種：Macbook air 2020 m1 ver.

**其他**
其他你覺得問題發生的疑點，或其他想跟小麥開發者說的話。
辛苦了！！很好用

**Comment by lukhnos** [comment]
目前在程式裡限制最長只能打 20 個字。如果願意從原始碼編，可以自己改。要注意的是，目前的選字演算法執行時間呈指數成長，所以組字區長了之後打下一個字會很慢。30-40 現在的電腦或許可以撐住，1500 應該是沒辦法的。

因為 20 個字的限制是從程式碼寫死，這個問題我會說是 "work as intended"。這個問題確實不是頭一次有人提了。我開了 #309 留作紀錄。

**Comment by Nighteye841228** [comment]
了解，謝謝你們的回應👍
