### ISSUE TITLE
[功能建議] 選字功能列表更新

### ISSUE THREAD

**Issue by Cookie755233** [OpenVanilla/McBopomofo#310]
**痛點**
剛入手mac的時候十分不習慣他的輸入法，所以找到了小麥，但是在選字的部分還是有幾個部分希望更新

**功能說明**
1. 下拉選單美化設定
下拉選單的設計能夠符合MacOS設計風格，如圓角、透明度、字型等。
或能夠於 preferences 裡面（或資料夾內config檔）讓我們自己設定下拉選單的樣式，現在的下拉選單看起來實在是太古老了 :(
_如隔壁squirrel輸入法有提供squirrel.custom.yaml檔能夠客製化自己的介面_

3. 下拉選單顯示所有替換詞選項
MAC 原生選單若將 Candidate Window 選則橫向，在選字時會按下可以將所有候選顯示出來（直式沒有），
希望也能夠新增此功能。
`https://i.imgur.com/eSYZSBO.jpg`

感謝！

**Comment by larryjclai** [comment]
如果選字清單有機會跟原生一樣感覺很棒！

**Comment by shuang886** [comment]
In contrast, built-in Zhuyin looks like this:

<img width="275" alt="Screenshot 2023-11-22 at 10 06 58 AM" src="https://github.com/openvanilla/McBopomofo/assets/140762048/6313980c-ef92-4c75-8c08-13630d33b25b">

<img width="210" alt="Screenshot 2023-11-22 at 10 04 04 AM" src="https://github.com/openvanilla/McBopomofo/assets/140762048/6255e595-365a-4451-b335-6cebd9d56ba5">

**Comment by shuang886** [comment]
字型讓使用者自選似乎不妥。如果不小心選了個缺字較多的字體，結果應該是更難看。`VerticalCandidateController` 依靠 `NSTextFieldCell` 的部分好像也得改寫為 view-based。

至於「顯示所有候選」的部分，要改寫的範圍就大很多了。

**Comment by shuang886** [comment]
「顯示所有候選字詞」和「自己設定下拉選單」並未解決，@Cookie755233 如果覺得這兩樣很重要請重開議題。
