### ISSUE TITLE
[功能建議] 支援開啟從 Finder 建立的詞庫檔案替身 (alias)

### ISSUE THREAD

**Issue by jmedzen** [OpenVanilla/McBopomofo#312]
**痛點**
-剛開始入手，比內建的好用！
-但發現使用者自訂詞庫沒辦法多機同步。
-如果有使用兩台以上mac會遇到的問題。

**功能說明**
-就是 ~/Library/Application Support/McBopomofo/data.txt 沒辦法指定到雲端去給其他機器使用/同步
-其他的軟體像是unclutter，他是能手動指定這類檔案的path。
![image](https://user-images.githubusercontent.com/3854265/164953223-17484c4d-193f-4bae-b24d-4c31d41960bb.jpeg)

-試過製作替身，把實體檔案丟到dropbox。但是小麥就不能編輯檔案了。

**替代方案**
NA

**其他**
辛苦了！

**Comment by lukhnos** [comment]
謝謝提供這個建議。有沒有試過從終端機建立 symlink ？例如我把詞庫檔放在 `~/Downloads`，然後我可以用以下指令建立自訂詞庫檔案的 symlink:

```
ln -s ~/Downloads/data.txt ~/Library/Application\ Support/McBopomofo/data.txt
```

Finder alias 跟 POSIX symlink 運作方式不一樣。如果自訂詞庫檔改用 symlink 放在小麥用戶資料夾中，應該可以滿足「實體檔案放在 Dropbox 供多台 Mac 同步」的需求。

**Comment by zonble** [comment]
開發版本中已經有這個功能了，先關票 :)
