### ISSUE TITLE
分號快捷鍵

### ISSUE THREAD

**Issue by mjhsieh** [openvanilla/McBopomofo#32]
wastemobile wastemobile 
小麥輸入的分號快捷鍵，是 shift + 「'」，真怪。冒號與分號的確應該要能夠按空白鍵互選才對，與鍵盤對應相符；「"」與「'」也是。

**Comment by zonble** [comment]
現在可以透過自訂詞表格修改

加上了說明文件 https://github.com/openvanilla/McBopomofo/wiki/%E4%BD%BF%E7%94%A8%E8%AA%AA%E6%98%8E_%E6%BC%A2%E9%9F%B3%E9%A2%A8%E6%A0%BC%E6%A8%99%E9%BB%9E%E7%AC%A6%E8%99%9F
