### ISSUE TITLE
[詞庫問題回報] Symbols.txt 裡面 😀 以下的都不會出現在選單中

### ISSUE THREAD

**Issue by griiid** [OpenVanilla/McBopomofo#324]
**分類**

- [ ] 錯字或錯誤讀音
- [ ] 缺字/詞
- [x] 其他

**說明**
在 Symbols 檔案裡面，從 😀 開始，以下的全部符號都打不出來
例如輸入「ㄒㄧㄠˋ」，選字選單裡面不會出現「😀」這個符號
在他上面的我隨機抓了幾個測試都會出現

另外想順便請教這個檔案每一行後面的 -8 是做什麼用的？

**相關資料**
檔案是：https://github.com/openvanilla/McBopomofo/blob/master/Source/Data/Symbols.txt

**Comment by lukhnos** [comment]
2.2.2 版是 2022 年 2 月 20 日發布，而上述 emoji 是 3 月 2 號加入的，所以還沒有進入發行版本中… 😊

小麥詞條的分數是 log probability, `-8` 是個手工挑的一個很低的機率，用這個常數讓用戶選字記憶機制不要記住 emoji 等符號的選字，這樣下次打「ㄒㄧㄠˋ」時才不會把 emoji 當成最優先出的候選字。
