### ISSUE TITLE
[功能建議] 希望能透過數字鍵區的數字選字

### ISSUE THREAD

**Issue by aowakennomai** [OpenVanilla/McBopomofo#345]
**痛點**
1. 使用數字選字時，按下數字鍵區(九宮格區域)的數字會變成直接輸入該數字，而非選取該數字對應的候選字。

**功能說明**
1. 除了打字鍵區的數字，也能透過數字鍵區的數字選字。

**替代方案**
1. 繼續使用打字鍵區的數字選字。

**其他**
感謝各位辛苦的付出 :)

**Comment by shuang886** [comment]
欲開啟功能，請在終端機裡輸入以下指令：

```
defaults write org.openvanilla.inputmethod.McBopomofo SelectCandidateWithNumericKeypad -bool YES
```

要關閉就改為 `NO` 即可。如果您認為這應該有圖形介面設定，請另外寫一個 Issue 以便追蹤。
