### ISSUE TITLE
[詞庫問題回報] 2023 Q1 詞庫更新專用

### ISSUE THREAD

**Issue by mjhsieh** [OpenVanilla/McBopomofo#353]
**分類**

- 錯字或錯誤讀音
- 缺字/詞
- [ ] 其他

**說明**
請說明是哪個字寫錯或是標音錯誤，以及正確的寫法與念法。

**相關資料**
像是字典的連結等。

**Comment by xatier** [comment]
週延 -> 周延
Ref: https://www.moedict.tw/%E5%91%A8%E5%BB%B6
