### ISSUE TITLE
[詞庫問題回報]缺字「綉」

### ISSUE THREAD

**Issue by PattyZou** [OpenVanilla/McBopomofo#364]
**分類**

- [ ] 錯字或錯誤讀音
- 缺字/詞
- [ ] 其他

**說明**
缺少「綉」字，讀音ㄒ一ㄡˋ，繡的異體字。

**相關資料**
[字典連結](https://dict.revised.moe.edu.tw/dictView.jsp?ID=107570&word=%E7%B6%89#searchL)

**Comment by xatier** [comment]
@lukhnos would you like to close this ticket?
