### ISSUE TITLE
[功能問題回報]輸入法列表會有重複的小麥注音

### ISSUE THREAD

**Issue by hsumingkai** [OpenVanilla/McBopomofo#365]
**快速分類**
請問您遇到的是：
- [o] UI 顯示不正常

**問題發生步驟**
1. 當我升級macOS 13.4.1
2. 輸入法列表會有重複的小麥注音，且隨時間會越來越多(不確定會越來越多的觸發條件

**螢幕截圖或螢幕錄製**
<img width="332" alt="截圖 2023-06-23 下午2 16 49" src="https://github.com/openvanilla/McBopomofo/assets/47695321/31667c8b-00dc-4501-810c-ed9e4cd14df1">
<img width="332" alt="截圖 2023-06-23 下午2 16 49" src="https://github.com/openvanilla/McBopomofo/assets/47695321/f2954db8-c3f8-409c-93a8-31cb25287407">

**電腦環境**
macOS 13.4.1

- 小麥注音版本：（請填寫版本）
- 鍵盤樣式：
  - [x] 標準
- macOS 版本：macOS 13.4.1
- 電腦機種：macbook pro

**Comment by lukhnos** [comment]
請參考 [wiki 上這個常見問題](https://github.com/openvanilla/McBopomofo/wiki/常見問題#我的輸入法選單出現了兩個三個甚至五個小麥注音的圖示)的說明，看看是否能完全移除重複的輸入法選項。
