### ISSUE TITLE
[功能建議] 詞庫更新指引

### ISSUE THREAD

**Issue by xatier** [OpenVanilla/McBopomofo#369]
**痛點**

This feature request is from https://github.com/openvanilla/McBopomofo/pull/368. 

**功能說明**

There's no contributor guidelines or tooling for updating the data files.

Ideally, we need some contributor guidelines on updating the data files, to avoid breaking ordering issues like this instance. The guides should cover things like which files to edit, in which order, any special considerations, etc.

If such guides were provided, I wouldn't mind writing some scripts for easier updates.

**替代方案**

Currently, I'm simply checking the missing phrases/characters by grepping the repo, inserting the missing data without knowing the proper data orders of the edits. @lukhnos helped review the PRs and provided suggestions.

**其他**
其他你想跟小麥注音開發團隊說的話。

**Comment by zonble** [comment]
我簡單寫了一份

https://github.com/openvanilla/McBopomofo/wiki/%E8%A9%9E%E5%BA%AB%E9%96%8B%E7%99%BC%E8%AA%AA%E6%98%8E

**Comment by xatier** [comment]
This is very detailed, thank you!
