### ISSUE TITLE
Caps Lock 打開時，方向鍵 + 英文 = 大寫

### ISSUE THREAD

**Issue by yllan** [openvanilla/McBopomofo#37]
在 Caps Lock on 時，按住方向鍵（上下左右任擇一），再按英文字母（例如 a）

預期結果：小寫字母 a

實際結果：大寫字母 A

**Comment by zonble** [comment]
話說這年頭蘋果都已經把 capslock 當成中英切換用的按鍵了，還要處理這個問題嗎？

**Comment by zonble** [comment]
這張票有點久，而且目前看起來沒有這個問題，先關掉好了。
