### ISSUE TITLE
[功能問題回報] Window title is unlocalized

### ISSUE THREAD

**Issue by shuang886** [OpenVanilla/McBopomofo#388]
**摘要**
See screenshot below, but the root cause is that `"%@ (for version %@, r%@)"` in **AppDelegate.swift**  is unlocalized:
```swift
window?.title = String(format: NSLocalizedString("%@ (for version %@, r%@)", comment: ""), window?.title ?? "", versionString, installingVersion)
```
because the available translations are old?
```
"%@ (for version %@)" = "%1$@ (for version %2$@)";
"%@ (for version %@)" = "%1$@ (%2$@ 版)";
```

Unfortunately, I don't really understand what `installingVersion` is so I don't feel comfortable translating it.

**快速分類**
請問您遇到的是：

- [ ] 當機或應用程式閃退
- [ ] 輸入法叫不出來，或無法正確輸出中文
- [ ] 無法切換到特定功能
- [ ] 輸入法效能有問題（執行速度太慢/電腦發燙）
- [X] UI 顯示不正常
- [ ] 其他

**螢幕截圖或螢幕錄製**
<img width="640" alt="Screenshot 2023-11-23 at 7 52 31 PM" src="https://github.com/openvanilla/McBopomofo/assets/140762048/e2aa348a-daa1-412c-8e1b-3407ac548798">

**Comment by lukhnos** [comment]
`versionString` is the human-readable `CFBundleShortVersionString` (like `2.5`) and the `installingVersion` is the monotonically-increasing `CFBundleVersion` number (like `1322`).

**Comment by shuang886** [comment]
So just:

```
"%@ (for version %@)" = "%1$@ (for version %2$@, r%3$@)";
"%@ (for version %@)" = "%1$@ (%2$@ 版，r%3$@)"
```

should be fine? I can put up a PR if you let me know how you’d like it translated.

**Comment by lukhnos** [comment]
> So just:
> 
> ```
> "%@ (for version %@)" = "%1$@ (for version %2$@, r%3$@)";
> "%@ (for version %@)" = "%1$@ (%2$@ 版，r%3$@)"
> ```
> 
> should be fine? I can put up a PR if you let me know how you’d like it translated.

The translation looks good to me. Much appreciated!
