### ISSUE TITLE
分類過的符號表

### ISSUE THREAD

**Issue by mjhsieh** [openvanilla/McBopomofo#39]
06:06:28 [@_Kyte_:1] @McBopomofo Hi，很高興看到一套新的輸入法出現，不知道能不能建議一些功能。
06:07:33 [@_Kyte_:2] @McBopomofo 按著shift+:的時候，希望能在按下空白鍵後，將「分號」也列入候選清單。
06:08:30 [@_Kyte_:3] @McBopomofo 希望能夠有類似香草那般整理過的符號輸入功能，因為我的工作需要大量的標點和符號，所以目前我一直沒辦法升級到10.6以上。
07:58:48 [@McBopomofo:5] @_Kyte_ 小麥注音目前只要按下 `按鈕，就可以出現一個標點符號列表。不知道這是不是您要的？
07:59:51 [@McBopomofo:6] @_Kyte_ 目前分號則是用 shift + '，這個主要是參考自然輸入法的排列方式。
08:12:44 [@_Kyte_:4] @McBopomofo 感謝回覆，我指的是如圖這樣ctrl+`按下去，出現的，可以更快選到要的符號。 http://t.co/FYDJUH7n
08:13:19 [@_Kyte_:5] @McBopomofo 好的，謝謝您的說明。

**Comment by zonble** [comment]
![截圖 2022-01-15 上午2 35 56](https://user-images.githubusercontent.com/53011/149567852-1f2f191d-5770-40a7-b03a-4a575fa7781b.png)

mac os 現在就有符號表了，感覺沒有必要跟作業系統做一樣的事情。

**Comment by zonble** [comment]
先關了好了。
