### ISSUE TITLE
mac 可以開啟 輸入法 ui 提示嗎

### ISSUE THREAD

**Issue by KScaesar** [OpenVanilla/McBopomofo#398]
**摘要**
我使用兩種 os, ubuntu 和 mac
發現在 ubuntu 使用小麥, 可以顯示輸入法提示
也就是當我要打字的時候, 會在當下的輸入欄位
出現 en 或 麥
來告知我現在是哪一種輸入法
想請問 mac 有辦法開啟相關設定嗎?

**快速分類**
請問您遇到的是：

- [ ] 當機或應用程式閃退
- [ ] 輸入法叫不出來，或無法正確輸出中文
- [ ] 無法切換到特定功能
- [ ] 輸入法效能有問題（執行速度太慢/電腦發燙）
- [ ] UI 顯示不正常
- [x] 其他

**電腦環境**
mac os

- 小麥注音版本：（請填寫版本）
- 鍵盤樣式：
  - [x] 標準
  - [ ] 倚天
  - [ ] 許氏
  - [ ] 倚天 26 鍵
  - [ ] 漢語拼音
  - [ ] IBM
 
- macOS 版本：（請填寫版本）
- 在哪個應用程式中打字遇到問題：（應用程式名稱/版本）
- 電腦機種：（筆電或桌機，使用 Intel 或 Apple Silicon CPU）
- 其他特殊設備：（請填寫是否有外接螢幕、特製鍵盤如非標準美式鍵盤等）
- 特殊設定：（是否原本正常，改了某個系統設定後就遇到問題）

**Comment by tianjianjiang** [comment]
> **摘要** 我使用兩種 os, ubuntu 和 mac 發現在 ubuntu 使用小麥, 可以顯示輸入法提示 也就是當我要打字的時候, 會在當下的輸入欄位 出現 en 或 麥 來告知我現在是哪一種輸入法 想請問 mac 有辦法開啟相關設定嗎?

就我所知，相近的功能要看 macOS 是否支援，而目前似乎只有 Sonoma 辦得到。
除非小麥另外做客製化 UI 元件。 +CC @lukhnos @zonble

**Comment by zonble** [comment]
其實有人寫了可以做到這個功能的軟體

https://inputsource.pro/

**Comment by zonble** [comment]
這個我先關掉，目前有可用的其他方案。
