### ISSUE TITLE
What happened to the Flatpak version?

### ISSUE THREAD

**Issue by stopusingthisplatformplease** [OpenVanilla/McBopomofo#400]
I installed McBopomofo via Flatpak on another machine a few weeks back, but can not find the package On Flathub anymore. What happened?

**Comment by stopusingthisplatformplease** [comment]
Nevermind, shows up in with flatpak search fcitx5. Just doesn't show on Flathub web ui.

**Comment by lukhnos** [comment]
Feel free to report any future fcitx5-mcbopomofo issues (incl. those with its Flatpak distribution) at https://github.com/openvanilla/fcitx5-mcbopomofo/issues

AFAIK you will only find fcitx5 itself with Flatpak web UI. Its input methods are considered add-ons and are listed separately under the "Add-ons" tab:

![1](https://github.com/openvanilla/McBopomofo/assets/25210/ab01c96f-197e-48f7-a6ce-a972e8451f9c)

And there one can find McBopomofo:

![2](https://github.com/openvanilla/McBopomofo/assets/25210/fd743c7b-81c2-4712-9460-27a21c2f8b3e)
