### ISSUE TITLE
[功能問題回報] 如何停用 Big5 內碼輸入功能

### ISSUE THREAD

**Issue by vock98** [OpenVanilla/McBopomofo#402]
**摘要**
我的VSCODE中 control+～是預設的開啟terminal快捷建
但是在小麥是內碼輸入法
但是我根本不會內碼輸入法
是否有辦法可以讓我不在使用內碼輸入法
把這個快捷建被我能拿回來使用

**快速分類**
請問您遇到的是：

- [ ] 當機或應用程式閃退
- [ ] 輸入法叫不出來，或無法正確輸出中文
- [O] 無法切換到特定功能
- [ ] 輸入法效能有問題（執行速度太慢/電腦發燙）
- [ ] UI 顯示不正常
- [ ] 其他

**問題發生步驟**

1. 打開 viscose
2. control+`

**預期正常狀況**
正常
但是會變成要我輸入內碼
我被迫要切換其他輸入法才能使用快捷建功能

**螢幕截圖或螢幕錄製**
應該不需要

**電腦環境**
MAC

- 小麥注音版本：（請填寫版本）
- 鍵盤樣式：
  - [x] 標準
  - [ ] 倚天
  - [ ] 許氏
  - [ ] 倚天 26 鍵
  - [ ] 漢語拼音
  - [ ] IBM
- macOS 版本： Mac Sonoma 14.2
- 在哪個應用程式中打字遇到問題：VSCODE
- 電腦機種： Apple Silicon CPU M2 MacBook Air
- 其他特殊設備：（請填寫是否有外接螢幕、特製鍵盤如非標準美式鍵盤等）
- 特殊設定：（是否原本正常，改了某個系統設定後就遇到問題）

**其他**
其他你覺得問題發生的疑點，或其他想跟小麥開發者說的話。

**Comment by lukhnos** [comment]
這樣的狀況，我們通常的作法是，在新版提供一個透過可從命令列更改的設定（例如[這些](https://github.com/openvanilla/McBopomofo/wiki/%E4%BD%BF%E7%94%A8%E8%AA%AA%E6%98%8E_%E5%85%B6%E4%BB%96%E5%8F%AF%E4%BB%A5%E9%80%8F%E9%81%8E%E7%B5%82%E7%AB%AF%E6%A9%9F%E8%AA%BF%E6%95%B4%E7%9A%84%E9%80%B2%E9%9A%8E%E8%A8%AD%E5%AE%9A)），來關掉或啟用特定功能。

不過因為我們才剛剛發過新版，目前也還有其他 feature work 正在進行。是否願意考慮自己透過編譯小麥注音的原始碼，來停用 Big5 內碼輸入法的功能？

**Comment by vock98** [comment]
下指令關閉我也ok

但是因為網路上說明只有提到

內碼輸入的呼叫方法

並沒有提到什麼命令可以關閉

如果可以的話

請告訴我，我要怎麼下命令關閉

感謝

Lukhnos Liu ***@***.***> 於 2023年12月19日 上午8:02 寫道：

﻿

這樣的狀況，我們通常的作法是，在新版提供一個透過可從命令列更改的設定（例如這些<https://github.com/openvanilla/McBopomofo/wiki/%E4%BD%BF%E7%94%A8%E8%AA%AA%E6%98%8E_%E5%85%B6%E4%BB%96%E5%8F%AF%E4%BB%A5%E9%80%8F%E9%81%8E%E7%B5%82%E7%AB%AF%E6%A9%9F%E8%AA%BF%E6%95%B4%E7%9A%84%E9%80%B2%E9%9A%8E%E8%A8%AD%E5%AE%9A>），來關掉或啟用特定功能。

不過因為我們才剛剛發過新版，目前也還有其他 feature work 正在進行。是否願意考慮自己透過編譯小麥注音的原始碼，來停用 Big5 內碼輸入法的功能？

**Comment by lukhnos** [comment]
我先前的留言可能沒有說明清楚：我們目前還沒有辦法關閉這個功能。

**Comment by zonble** [comment]
我來做個開關吧，不過這得要等下個版本發布才會一起出去。

**Comment by vock98** [comment]
好的

感謝大大

Weizhong Yang a.k.a zonble ***@***.***> 於 2023年12月19日 下午1:34 寫道：

﻿

我來做個開關吧，不過這得要等下個版本發布才會一起出去。
