### ISSUE TITLE
[功能問題回報]

### ISSUE THREAD

**Issue by olivertzeng** [OpenVanilla/McBopomofo#409]
在您回報問題之前，建議也可以先參考 Wiki 上的 [常見問題](https://github.com/openvanilla/McBopomofo/wiki/%E5%B8%B8%E8%A6%8B%E5%95%8F%E9%A1%8C) 與 [使用手冊](https://github.com/openvanilla/McBopomofo/wiki/%E4%BD%BF%E7%94%A8%E6%89%8B%E5%86%8A)

**摘要**
請簡單說明您遇到了什麼問題。這份表格雖然是中文的（我們相信注音輸入法的用戶應該都能看懂中文），但開發團隊可以使用中英文溝通，您也可以使用英文回報問題。

**快速分類**
請問您遇到的是：

- [ ] 當機或應用程式閃退
- [ ] 輸入法叫不出來，或無法正確輸出中文
- [ ] 無法切換到特定功能
- [ ] 輸入法效能有問題（執行速度太慢/電腦發燙）
- [ ] UI 顯示不正常
- [x] 其他

**問題發生步驟**

1. 打開 任何 app
2. 開始在 任何可以打字的地方 區域打字
3. 若欲輸出注音就會點擊打字的地方
4. 注音即輸出兩次

**預期正常狀況**
輸出一次注音

**螢幕截圖或螢幕錄製**
[螢幕錄影 20231229(1).webm](https://github.com/openvanilla/McBopomofo/assets/86348833/e16282f8-300f-46fe-b7da-c199a9e0c788)

**電腦環境**
請問您在怎樣的環境遇到這個問題？

- 小麥注音版本：（請填寫版本）
- 鍵盤樣式：
  - [x] 標準
  - [ ] 倚天
  - [ ] 許氏
  - [ ] 倚天 26 鍵
  - [ ] 漢語拼音
  - [ ] IBM
Operating System: Arch Linux 
KDE Plasma Version: 5.90.0
KDE Frameworks Version: 5.246.0
Qt Version: 6.6.1
Kernel Version: 6.6.8-zen1-1-zen (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 7735HS with Radeon Graphics
Memory: 14.9 GiB of RAM
Graphics Processor: AMD Radeon Graphics
Manufacturer: COPELION INTERNATIONAL INC.
Product Name: FORGE 16
System Version: Version 1.0
- 特殊設定： 無

**Comment by lukhnos** [comment]
fcitx5-mcbopomofo 的使用問題，請到 https://github.com/openvanilla/fcitx5-mcbopomofo/issues 回報，謝謝。
