### ISSUE TITLE
當輸入法當掉時，有沒有辦法可以不用重啟電腦，直接重啟輸入法？

### ISSUE THREAD

**Issue by benpptung** [OpenVanilla/McBopomofo#418]
最近連續兩天，在使用傳統注音輸入法時，當掉。當掉的情形一直都在，已經有可能 10 年了，我也不在意。但連續兩天實在太頻繁了。

當掉的原因: 不知道，看似很隨機。

當掉的情況：就是無法使用 cmd + space ，從英數切換成注音輸入，敲擊 cmd + space 無反應。

我只有添加傳統輸入法，如附圖。

![截圖 2024-01-10 上午9 55 41](https://github.com/openvanilla/McBopomofo/assets/364314/3feca379-eaf3-4a08-b408-33f4c8b35c26)

我在想，我可以在 terminal 殺掉某個 process ，讓這個輸入法恢復正常嗎？因為，每次都發生在，我開了好多 app, 檔案的時候，要重啟電腦真的有點麻煩。所以，在想說有沒有什麼簡單的方法，可以重啟這個輸入法。

**Comment by lukhnos** [comment]
在 Terminal 下可以輸入 `killall McBopomofo` 來重啟輸入法。

主要是，macOS 一直以來有個機制，一旦輸入法 process 重新載入超過一定次數，macOS 就不允許輸入法繼續提供服務了。這時候就算再怎麼 kill process，一樣沒有第三方輸入法可用。

如果問題其實已經很多年，那真的是困擾。請問方便看一下 Console.app 裡的 crash log，看看有無 McBopomofo 相關的 crash report 呢？另外也請提供目前使用的小麥注音版本，以及 macOS 版本，方便我們除錯。謝謝！
