### ISSUE TITLE
[功能建議] 調整候選字詞數量與可以在選字時，透過設定的按鍵切換

### ISSUE THREAD

**Issue by PlusoneChiang** [OpenVanilla/McBopomofo#422]
**痛點**
輸入時，需要頻繁使用方向鍵來移動游標，並且如果已經開啟候選字視窗後，
游標就無法移動了，必須要關閉候選字窗才能移動游標。
這樣就會讓右手頻繁離開主要按鍵區，降低輸入效率。

**功能說明**
1. 開啟候選字視窗後，可以額外指定功能按鍵來移動游標並開啟對應字/詞的候選字視窗。

個人使用情境：
候選字視窗字/詞數量設定為4，開啟候選字視窗後，
右手可以使用J、K移動游標並顯示對應候選字視窗，
左手按數字1234及空白鍵，切換並選擇要選定的字詞。

這樣就可以讓雙手在輸入時，盡可能的保持在主要按鍵區中，
而不需要在選字時需要頻繁的使用鍵位在鍵盤整體右下角的方向鍵。

這是在Windows環境下PIME輸入法實作的新酷音模組所提供的功能，
使用起來大概如以下影片
https://github.com/openvanilla/McBopomofo/assets/17397506/c34ed36d-283c-424d-856d-b08e6252fed0

**Comment by PlusoneChiang** [comment]
pull新的source code，build並安裝後，在中文環境中JK移動游標的功能設定不生效。
中文的設定頁面中，遺失Binding的設定。
<img width="653" alt="image" src="https://github.com/openvanilla/McBopomofo/assets/17397506/b26f53f8-d96d-489d-8642-7c132adab56e">
英文的設定頁面，Binding設定正常。
<img width="648" alt="image" src="https://github.com/openvanilla/McBopomofo/assets/17397506/bf681af6-fe87-43b4-8bc5-88d09f434cb6">

在中文設定頁面補上Binding設定後，測試功能正常！簡直完美！

**Comment by zonble** [comment]
那就是中文那邊有個 bug。方便發個 PR 嗎？
