### ISSUE TITLE
[功能建議] 自建使用者常用詞庫

### ISSUE THREAD

**Issue by chennien** [OpenVanilla/McBopomofo#443]
我很常打某些品牌名，如：「藍新金流」。
即使打了近百次，但出來的都是「藍心今流」，然後再手動選字。

請問未來是否可新增自建詞庫呢？
非常感謝。

**Comment by zonble** [comment]
目前的作法是，可以按住 Shift 以及左右鍵選擇一個範圍後，然後按下 Enter，就可以加入這個詞彙。可以先試試看這個功能是否可以滿足需求。

**Comment by chennien** [comment]
哇～ 太讚了！
超感謝 @zonble ，解決我多年來的痛點 (淚流滿面
甘蝦～～

> 目前的作法是，可以按住 Shift 以及左右鍵選擇一個範圍後，然後按下 Enter，就可以加入這個詞彙。可以先試試看這個功能是否可以滿足需求。

**Comment by zonble** [comment]
使用手冊都有寫啊⋯ 在 wiki 裡頭。
