### ISSUE TITLE
Keep BPMFMapping.txt and phrase.occ sorted

### ISSUE THREAD

**Issue by lukhnos** [OpenVanilla/McBopomofo#447]
From @xatier:

> On the ordering issue, I have this little script locally to keep my user dictionary nice and neat, I would suggest having sometime similar in this repo.

https://gist.github.com/xatier/9f34fb64884e3cbfd66f24716beb6e7a

_Originally posted by @xatier in https://github.com/openvanilla/McBopomofo/issues/437#issuecomment-1962227613_

**Comment by xatier** [comment]
I believe this can help our data sources to be easily maintainable :)

I'm simply relying on the default string ordering, we can also make a customized compare function for sorting in ㄅㄆㄇㄈ order with intonations.
