### ISSUE TITLE
[功能問題回報] 使用者自訂詞庫無法加入以 `#` 開頭的條目，因為會被視為註解。

### ISSUE THREAD

**Issue by jisa0224** [OpenVanilla/McBopomofo#458]
**摘要**

使用者自訂詞庫無法加入以 `#` 開頭的條目，因為會被視為註解。

**問題發生步驟**

Source/Data/BPMFPunctuations.txt 中紀錄了 `＃ _punctuation_# 0.0`。但我希望按下 `#` 按鍵能夠輸入**半形**的 `#`，因此我在個人詞庫中加入 `# _punctuation_#`，這樣可以讓選詞第一個項目是半形 `#`，但同時又能夠在需要的時候選取全形 `#`。

**預期正常狀況**

這其實是正常的，因為該項目被視為註解了。

希望增加某些方法 (如：第二個不包含註解的自訂詞庫檔案、某些特殊字元) 等方式規避此問題。

**電腦環境**

- 小麥注音版本：2.7.r2.5ceb365-1 (fcitx5)
- 鍵盤樣式：漢語拼音

**Comment by lukhnos** [comment]
這個需求可以透過「[手動換詞](https://github.com/openvanilla/McBopomofo/wiki/使用手冊#手動換詞)」這個進階功能來滿足：

* macOS 版: 小麥注音 2.7 版有 bug，手動換詞功能無法使用，#459 修正了，但要等待發新版。或者考慮裝回 2.6 版。
* fcitx5-mcbopomofo: 我們剛剛[加入了手動換詞功能](https://github.com/openvanilla/fcitx5-mcbopomofo/pull/139)，目前要從 source build 才能啟用該功能

作法是先在用戶詞庫中加入例如這樣的條目：

```
$$$$ _punctuation_#
```

然後，以 Ubuntu 為例，如果用戶詞庫存放在 `$HOME/.local/share/fcitx5/mcbopomofo/data.txt` 中，接下來就需要在同一個目錄建立手動換詞檔 `$HOME/.local/share/fcitx5/mcbopomofo/phrases-replacement.txt`，然後加入這一行：

```
$$$$ #
```

這樣一來，按 `#`，根據用戶詞庫，第一個候選詞原本該是 `$$$$`，但手動換詞機制換成了半形 `#`，這樣就是預期的結果了。

請看看這樣是否合用。我們先關閉這張回報。如果有後續跟 fcitx5-mcbopomofo 相關的問題，可以到該專案回報或繼續討論: https://github.com/openvanilla/fcitx5-mcbopomofo/issues

**Comment by jisa0224** [comment]
你好，我已使用 <https://github.com/openvanilla/fcitx5-mcbopomofo/pull/139> 進行編譯後測試，可以完美解決此問題。

十分感謝！
