### ISSUE TITLE
[詞庫問題回報] 輸入法是否會學習常用字選擇？

### ISSUE THREAD

**Issue by TTSoong** [OpenVanilla/McBopomofo#461]
**分類**

- [ ] 錯字或錯誤讀音
- [ ] 缺字/詞
- [ X ] 其他

**說明**
常用字會學習嗎？不是很理解ㄓㄢˋ這個讀音首選字是為什麼是戰，對於一個網站使用者，一直要針對這個字做選字有點累。

**相關資料**

**Comment by tianjianjiang** [comment]
> 不是很理解ㄓㄢˋ這個讀音首選字是為什麼是戰，對於一個網站使用者，一直要針對這個字做選字有點累。

注音輸入法裡有不少單音節的排序確實很奇特。某方面說來是個無奈的歷史因素。

Open source 輸入法的注音表格往往來自 XCIN, 而 XCIN 多多少少模仿了最初的幾個中文系統 (e.g., 倚天)。由於當時不少使用者已經連某字在候選列表裡第幾位都背下來 (好比說用大千鍵盤的使用者輸入「站」時可能會反射性地打 5042)，所以後來的輸入法通常不太敢改變那些排序。

**Comment by TTSoong** [comment]
感謝回覆，我只是想確認一下小麥會不會學習，相較原生繁體注音及超注音來說，依然瑕不掩瑜。

**Comment by lukhnos** [comment]
@tianjianjiang 提到了歷史緣由。這邊做點補充：

> 常用字會學習嗎？

會… 但其中有細節。例如在行首打ㄓㄢˋ，出現「戰」後選「站」。或是在行首打「場戰」然後把「戰」改為「站」、打「這一戰」然後把「一戰」改選為「一站」，之後這個選字或選詞就會被記下來。不過，輸入法大約會在一天後「忘掉」這個選擇。會這樣設計是經過一些實驗後的取捨。

如果經常用到「站」跟相關詞，可以透過[用戶自訂詞功能](https://github.com/openvanilla/McBopomofo/wiki/使用手冊#進階手動加詞玩法)，加入例如下列條目：

```
# 讓單字詞的「站」永遠優先於「戰」，這樣一來就算是打「場站」「站點」等小麥目前未收錄的詞，也不會先出現「戰」
站 ㄓㄢˋ
# 讓「一站」優先順序高過「一戰」這個收錄詞
一站 ㄧˊ-ㄓㄢˋ
```

**Comment by xatier** [comment]
@lukhnos 這個說明很好，也許我們將這段加入使用手冊內？

https://github.com/openvanilla/McBopomofo/wiki/%E4%BD%BF%E7%94%A8%E6%89%8B%E5%86%8A#%E6%89%8B%E5%8B%95%E6%8F%9B%E8%A9%9E

**Comment by lukhnos** [comment]
> @lukhnos 這個說明很好，也許我們將這段加入使用手冊內？
> 
> https://github.com/openvanilla/McBopomofo/wiki/%E4%BD%BF%E7%94%A8%E6%89%8B%E5%86%8A#%E6%89%8B%E5%8B%95%E6%8F%9B%E8%A9%9E

Done: https://github.com/openvanilla/McBopomofo/wiki/使用手冊#透過手動加詞調整候選詞順序
