### ISSUE TITLE
[功能問題回報]切換中英文輸入時，在輸入點出現的藍底白字小提示不見了？

### ISSUE THREAD

**Issue by Darkfunner** [OpenVanilla/McBopomofo#470]
**摘要**
如題，本來在按下caps lock鍵切換中英文時，輸入點都會出現一個短暫的小提示框顯示「ㄅ」「A」讓使用者直觀感受到已經切換輸入法，但是當我安裝了一個乾淨的新系統(Ventura 13.6.6)，重新安裝小麥後，這個提示不見了（中英文有正常切換，單純就是這個提示不見了）

**快速分類**
請問您遇到的是：
- [ ] UI 顯示不正常

**問題發生步驟**
請問您是怎麼遇到這個問題的？像是：
切換到某種設定..

請問您在怎樣的環境遇到這個問題？
- 小麥注音版本：2.7.2
- 鍵盤樣式：
  - [x] 標準

- macOS 版本：13.6.6
- 電腦機種：iMac 27 2020 intel
- 特殊設定：原本正常，重新乾淨安裝系統後遇到問題

**Comment by zonble** [comment]
我記得輸入法切換顯示是 macOS 15 的功能。因為您重裝了舊版的系統，就沒有這項功能了。
