### ISSUE TITLE
[功能問題回報] 安裝小麥注音後沒有出現於系統輸入法選單

### ISSUE THREAD

**Issue by vincent5753** [openvanilla/McBopomofo#471]
在您回報問題之前，建議也可以先參考 Wiki 上的 [常見問題](https://github.com/openvanilla/McBopomofo/wiki/%E5%B8%B8%E8%A6%8B%E5%95%8F%E9%A1%8C) 與 [使用手冊](https://github.com/openvanilla/McBopomofo/wiki/%E4%BD%BF%E7%94%A8%E6%89%8B%E5%86%8A)

**摘要**
如題，我按照 [安裝小麥注音輸入法](https://github.com/openvanilla/McBopomofo/wiki/%E4%BD%BF%E7%94%A8%E6%89%8B%E5%86%8A#%E5%AE%89%E8%A3%9D%E5%B0%8F%E9%BA%A5%E6%B3%A8%E9%9F%B3%E8%BC%B8%E5%85%A5%E6%B3%95) 安裝後系統設定並未出現小麥注音的選項

**快速分類**
請問您遇到的是：
- [ ] 當機或應用程式閃退
- [x] 輸入法叫不出來，或無法正確輸出中文
- [ ] 無法切換到特定功能
- [ ] 輸入法效能有問題（執行速度太慢/電腦發燙）
- [ ] UI 顯示不正常
- [ ] 其他

**問題發生步驟**
請問您是怎麼遇到這個問題的？像是：

1. 按照建議安裝步驟安裝輸入法後，打開系統設定的鍵盤選項

**預期正常狀況**
輸入法出現於設定中

**螢幕截圖或螢幕錄製**
系統輸入法設定
<img width="827" alt="image" src="https://github.com/openvanilla/McBopomofo/assets/29014142/ed44c007-fbf5-4b4d-ae6f-324dad5d6fa5">

`~/Library/Input Methods` 路徑
<img width="1322" alt="image" src="https://github.com/openvanilla/McBopomofo/assets/29014142/69a10b8e-f61a-4fcc-9d0d-9be43f5e53ca">

**電腦環境**
masOS: 14.4.1
<img width="392" alt="image" src="https://github.com/openvanilla/McBopomofo/assets/29014142/27c6b28e-c663-48f3-a009-97ec342c1b07">

- 小麥注音版本：（請填寫版本）
- 鍵盤樣式：
  - [x] 標準
  - [ ] 倚天
  - [ ] 許氏
  - [ ] 倚天 26 鍵
  - [ ] 漢語拼音
  - [ ] IBM
- macOS 版本：14.4.1
- 在哪個應用程式中打字遇到問題：安裝後未出現於系統設定
- 電腦機種：Apple Silicon M2
- 其他特殊設備：內建螢幕
- 特殊設定：無特殊設定

**其他**
無

**Comment by lukhnos** [comment]
想確認兩件事情：

1. 小麥注音安裝後，macOS 的「系統設定」是否有出現 `「安裝小麥注音」想要啟用第三方輸入法「小麥注音」。` 的提示？（見附圖）
2. 上述截圖中有看到 OpenVanilla，但確實沒看到小麥注音。如果登出後再登入（或是重新開機），是否能在文字輸入方式的選單中，找到小麥注音？

<img width="398" alt="post-install-confirmation" src="https://github.com/openvanilla/McBopomofo/assets/25210/ebeb22c1-be1b-4717-a2f4-dcb627824350">

**Comment by vincent5753** [comment]
您好，我在重新開機後再次嘗試安裝後
設定有出現您所說的安裝第三方輸入法的選單了
<img width="264" alt="image" src="https://github.com/openvanilla/McBopomofo/assets/29014142/1ba8b129-ecf6-4f77-8cd9-31742cae4b52">
