### ISSUE TITLE
[功能問題回報] 請問如何增加新字

### ISSUE THREAD

**Issue by miniric** [OpenVanilla/McBopomofo#478]
**摘要**
上次有在這邊詢問甯的另外一個字，寶蓋＋必＋冉。很感謝團隊似乎以加入新字。但我這邊local的輸入法仍是找不到該字。
請問是需要使用者自行更改code嗎？還是要如何才能看到新增加的字？

**快速分類**
- [ ] 新字找不到

**預期正常狀況**
新創建字已可於搜尋欄位找到

**電腦環境**
MAC 最新作業系統

- 小麥注音版本：（請填寫版本）
- 鍵盤樣式：
  - [x] 標準
  
- macOS 版本：（Sonoma)

**其他**
感謝團隊上次迅速的回覆，輸入法蠻好用的

**Comment by lukhnos** [comment]
> 但我這邊local的輸入法仍是找不到該字。

對，因為詞庫原始碼更新後，還得等下一次小麥注音發行新版，才會收錄進去。

除了自行編譯小麥注音原始碼外，另一個作法是透過手動加詞，把自己需要的字或詞加進詞庫中: https://github.com/openvanilla/McBopomofo/wiki/使用手冊#手動加詞
