### ISSUE TITLE
空白鍵在候選詞窗內的行為 - 選字(?)

### ISSUE THREAD

**Issue by mjhsieh** [openvanilla/McBopomofo#49]
(google plus)vince chen  -  非常期待自動學習和詞庫匯入的功能，還有，能不能順便考慮一下選字直接按空白鍵（像古早以前WINDOWS版本的漢音輸入法一樣）？加油，期待。
@mjhsieh - works for me.
(google plus)vince chen  -  您誤會我的意思了，我指的是按第一次空白鍵選候選字列表裡的第一個字，按第二次空白鍵選候選字列表裡的第二個字，依此類推。：）這個功能如果搭配尚未推出的自動學習和自定詞庫功能，應該會如虎添翼。非常期待新版的推出，你們辛苦了，一定要加油啊。

**Comment by zonble** [comment]
這麼多年了，關了吧…。

**Comment by ShikiSuen** [comment]
@zonble 這種問題的決策取捨真的得看實際使用者數量來。
漢音輸入法當年有些獨特的設計，不見得就是最近一兩代人學注音時接觸到的習慣方式。
（打比方說漢音的標點模式那種情況好了，當年微軟的ㄅ半注音連漢語標點符號都無法正常輸入，繁體中文版 Word 97 還專門內建了輸入中文標點用的巨集。）
