### ISSUE TITLE
[詞庫問題回報] 缺少 “葤” 這個字

### ISSUE THREAD

**Issue by Dominikggd** [OpenVanilla/McBopomofo#509]
您好，因為近期文書處理工作需要經常用到，
發現目前打注音 ㄓㄡˋ 的時候沒有 “葤” 這個候選字可以選，
但切回蘋果繁體中文注音有“葤”可以選擇，
確實這個字相當少見，但希望可以更新加入資料庫，謝謝小麥注音團隊。

線上字典：
https://dict.variants.moe.edu.tw/dictView.jsp?ID=100573&q=1

**Comment by seekfoo** [comment]
最近回報了系統缺字，爬文發現這個"葤"已回報近三個月，小麥注音卻還是打不出這個 ㄓㄡˋ 字。
請問回報後需等候多久才會等來更新？謝謝

**Comment by zonble** [comment]
這張 issue 七月的時候就已經處理了，在目前的 2.8.1 版本中也已經可以打出這個字。

**Comment by seekfoo** [comment]
謝謝說明，請問小麥注音的「檢查是否有新版」功能是否運作異常？
我目前的版本為 版本2.7.2（1595），但在輸入法上按右鍵後，選擇"檢查是否有新版..."
系統都是回覆，您的小麥注音不需要更新。

還是我一定要到官網下載最新版、安裝，才能夠維持最新版本呢？


https://github.com/user-attachments/assets/d94d28a9-8bfb-42ad-bdc1-9ec6e2aab3f3

**Comment by lukhnos** [comment]
伺服器上的版本更新資訊發布晚了。正好有其他用戶問到，請參考這邊的說明: https://github.com/openvanilla/McBopomofo/issues/550#issuecomment-2449292355
