### ISSUE TITLE
是否也能導入ML底下的shift+6的顏文字功能呢

### ISSUE THREAD

**Issue by ghost** [openvanilla/McBopomofo#54]
不好意思連續開了兩篇討論串，畢竟這兩個問題是不一樣的

ML新增的顏文字功能滿好用的，不曉得可不可以導入這個功能呢？

另外也謝謝您的開發與維護

**Comment by lukhnos** [comment]
595d81d610231f2024deff6e7590e3005b2a765d 誤植，該 commit 修正的是 #154 而非 #54。

**Comment by zonble** [comment]
其實我不太懂這是哪個功能。macOS 的 emoji 不就是從 Edit 選單中叫出 emoji 面板嗎？

**Comment by zonble** [comment]
這個功能現在可以用自訂詞達成。

https://github.com/openvanilla/McBopomofo/wiki/%E4%BD%BF%E7%94%A8%E8%AA%AA%E6%98%8E_Shift_6_%E7%AC%A6%E8%99%9F%E8%A1%A8
