### ISSUE TITLE
[功能問題回報] 檢查更新時顯示是最新版，但是實際上不是

### ISSUE THREAD

**Issue by yuchiachang** [OpenVanilla/McBopomofo#550]
**摘要**
檢查更新時顯示是最新版，但是實際上不是。

**快速分類**
請問您遇到的是：

- [ ] 當機或應用程式閃退
- [ ] 輸入法叫不出來，或無法正確輸出中文
- [ ] 無法切換到特定功能
- [ ] 輸入法效能有問題（執行速度太慢/電腦發燙）
- [ ] UI 顯示不正常
- [x] 其他

**問題發生步驟**
請問您是怎麼遇到這個問題的？像是：

1. 從選單上選取 Check for updates...
2. 視窗顯示是最新版 (McBopomofo is up to date.)
3. 從選單上選取 About McBopomofo...
4. 視窗顯示是 version 2.7.2
5. 從Github上看，最新的版本應該是 2.8.1 (2024/10/25)

**預期正常狀況**
從選單上選取 Check for updates... 之後應該會通知有更新。

**螢幕截圖或螢幕錄製**
<img width="487" alt="SCR-20241025-tiln" src="https://github.com/user-attachments/assets/9837b605-748b-4c21-a3d4-4952db5a61e7">

**電腦環境**
請問您在怎樣的環境遇到這個問題？

- 小麥注音版本：2.7.2
- 鍵盤樣式：
  - [x] 標準
  - [ ] 倚天
  - [ ] 許氏
  - [ ] 倚天 26 鍵
  - [ ] 漢語拼音
  - [ ] IBM
- macOS 版本：Sonoma 14.7
- 在哪個應用程式中打字遇到問題：N/A
- 電腦機種：Mac Studio M1 Max
- 其他特殊設備：無
- 特殊設定：無

**其他**
其他你覺得問題發生的疑點，或其他想跟小麥開發者說的話。

**Comment by xatier** [comment]
The update API [1] seemed to return the old version. Perhaps we need to also update the SoT of this API to point to the latest version on GitHub.

```bash
$ curl -L 'http://mcbopomofo.openvanilla.org/updates/Info.plist?manual=yes'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>UpdateInfoEndpoint</key>
        <string>http://mcbopomofo.openvanilla.org/updates/Info.plist</string>
        <key>UpdateInfoSite</key>
        <string>http://mcbopomofo.openvanilla.org</string>
        <key>CFBundleVersion</key>
        <string>1595</string>
        <key>CFBundleShortVersionString</key>
        <string>2.7.2</string>
        <key>Description</key>
        <dict>
        <key>en</key>
        <string>* Fix faulty "new version available" dialog box
* Date macros
* Improved associated phrases
* Braille support
* Advanced output options and inline conversions
* Online dictionaries lookup
* Improved user experience
* Phrases database update</string>
        <key>zh-Hant</key>
        <string>* 修正新版通知的對話盒按鈕位置錯誤 
* 日期巨集
* 聯想詞功能更新
* 點字輸出及轉換
* 多種進階輸出及數字轉換功能
* 線上詞典查找
* 用戶體驗改進
* 詞典更新</string>
</dict>
</dict>
</plist>
```

[1] https://github.com/openvanilla/McBopomofo/blob/master/Source/AppDelegate.swift#L61

**Comment by lukhnos** [comment]
剛剛在伺服器上發布了版本更新資訊。

小麥發布新版後，通常隔一段時間，我們才會在伺服器上發布版本更新資訊。三個原因：

技術上，我們希望等新版穩定後，再來發布通知。

人力上，開發者們平日有正職，許多事務要有空才能處理。

最後一個是歷史因素：我們目前讓最近幾個版本的小麥注音，在手動檢查更新時，會跟伺服器拿到最新的發布消息（當然，這前提是伺服器上的資訊得要更新）。至於自動更新檢查，由於小麥的版本檢查機制很簡單，加上我們還有許多過往 macOS 版本以及小麥注音版本用戶得考慮，所以我們還在緩慢地進行這部分的工作。

不過 @xatier 講的有道理，我們應該來想想怎麼讓版本更新的 source of truth 指向 GitHub release info，或至少讓這兩者同步的時間差小一點。

**Comment by lukhnos** [comment]
這次趁 2.9.0 版發布，一併更新了伺服器上的版本更新資訊。我們也採取分批方式發布，這樣用戶看過一次版本更新通知，隔一陣子後才會再次看到提醒。

手動檢查的話，自 2.5 版開始，就總是會收到最新的版本資訊了。
