### ISSUE TITLE
[功能問題回報] 打不出"祢"這個字

### ISSUE THREAD

**Issue by seekfoo** [OpenVanilla/McBopomofo#551]
**摘要**
打不出"祢"這個字

**快速分類**
請問您遇到的是：

- [ ] 當機或應用程式閃退
- [x] 輸入法叫不出來，或無法正確輸出中文
- [ ] 無法切換到特定功能
- [ ] 輸入法效能有問題（執行速度太慢/電腦發燙）
- [ ] UI 顯示不正常
- [ ] 其他

**問題發生步驟**
請問您是怎麼遇到這個問題的？像是：

打不出"祢"這個字，ㄋㄧˇ
教育部字典 https://dict.revised.moe.edu.tw/dictView.jsp?ID=30855&la=0&powerMode=0

**電腦環境**
請問您在怎樣的環境遇到這個問題？
Mac OS 版本15.0.1（24A348）
小麥注音 版本2.7.2（1595）

- 小麥注音版本：（請填寫版本）
- 鍵盤樣式：
  - [x] 標準
  - [ ] 倚天
  - [ ] 許氏
  - [ ] 倚天 26 鍵
  - [ ] 漢語拼音
  - [ ] IBM
- macOS 版本：15.0.1（24A348）
- 在哪個應用程式中打字遇到問題：全部
- 電腦機種：macbook pro
- 其他特殊設備：有外接螢幕
- 特殊設定：

**其他**
其他你覺得問題發生的疑點，或其他想跟小麥開發者說的話。

**Comment by xatier** [comment]
Fixed in https://github.com/openvanilla/McBopomofo/pull/552
