### ISSUE TITLE
[功能問題回報]

### ISSUE THREAD

**Issue by jacky4gia** [OpenVanilla/McBopomofo#554]
請教可以增加  （ㄍㄥ） 畊   這個字 嗎 ？

**Comment by lukhnos** [comment]
小麥注音輸入法選單中有個「編輯使用者詞彙」的功能，可以在那邊加入用戶自訂字詞，參考看看: https://github.com/openvanilla/McBopomofo/wiki/使用手冊#手動加詞

**Comment by zonble** [comment]
#555 已經加入了這個字。
