### ISSUE TITLE
自訂符號輸入法。

### ISSUE THREAD

**Issue by mjhsieh** [openvanilla/McBopomofo#57]
From twitter

Pawf ‏@teix510
@McBopomofo 請問可不可以像Windows上的新酷音一樣自訂符號表？

**Comment by xatier** [comment]
We should have that with `Shift-6`?

Ref: https://github.com/openvanilla/McBopomofo/wiki/%E4%BD%BF%E7%94%A8%E8%AA%AA%E6%98%8E_Shift_6_%E7%AC%A6%E8%99%9F%E8%A1%A8

**Comment by lukhnos** [comment]
確實，有了自訂詞後，符號表可以用這個方式解決。甚至按 ` 所顯示的符號表，也可以用自訂詞方式新增條目。新增的符號會出現在內建的符號前。例如：

```
！ _punctuation_list                                                                                                                                           
？ _punctuation_list 
```
