### ISSUE TITLE
建議加入進階設定的 wiki 頁面。

### ISSUE THREAD

**Issue by jamessa** [openvanilla/McBopomofo#66]
_Purposed wiki page._
# 進階設定

支援特定的英文鍵盤格式，但是小麥在其他鍵盤輸入的配置，預設值仍然是 US Keyboard (`com.apple.keylayout.US`)
## Colemak + QWERTY ⌘

```
defaults write org.openvanilla.inputmethod.McBopomofo FunctionKeyKeyboardLayout -string "com.apple.keylayout.Colemak"
defaults write org.openvanilla.inputmethod.McBopomofo FunctionKeyKeyboardLayoutOverrideIncludeShift -bool true
```

這兩個鍵碼的功用為：
1. 遇到功能鍵時，使用特別設定的 layout (`FunctionKeyKeyboardLayout`，本例中為 Colemak)
2. Shift 鍵的組合也是功能鍵的一種 (`FunctionKeyKeyboardLayoutOverrideIncludeShift`)

之所以會需要第二個鍵碼，是因為有些使用者（例如 Dvorak）習慣在切換到注音後，連標點符號也要改用（沿用上例）Dvorak 配置。這樣的使用者得將 Shift 也當作功能鍵的一種。如果你的需求只是需要 Cmd 等組合鍵要用 Colemak，而標點符號也使用 QWERTY，那只要設第一個鍵碼就可以了（第二個鍵碼的預設是 `false`）。
## Dvorak + QWERTY ⌘

```
defaults write org.openvanilla.inputmethod.McBopomofo FunctionKeyKeyboardLayout -string "com.apple.keylayout.Dvorak"
defaults write org.openvanilla.inputmethod.McBopomofo FunctionKeyKeyboardLayoutOverrideIncludeShift -bool true
```

**Comment by zonble** [comment]
See [進階鍵盤配置](../wiki/進階鍵盤配置)
