### ISSUE TITLE
請問有模擬鍵盤嗎?

### ISSUE THREAD

**Issue by seannkate** [openvanilla/McBopomofo#70]

**Comment by zonble** [comment]
模擬鍵盤還是沒有，手冊倒是寫了 https://github.com/openvanilla/McBopomofo/wiki/%E4%BD%BF%E7%94%A8%E6%89%8B%E5%86%8A

**Comment by ShikiSuen** [comment]
模擬鍵盤正是我之前提出使用 apple bopomofo keyboard layout 的誘因之一。
然而因為 Formosa 引擎本身的特性、以及小麥注音多鍵盤佈局支援的原因而只能暫時作罷。
魚與熊掌不可兼得。要想讓小麥做到這一點的話，小麥恐需要自己弄一套自己的螢幕鍵盤。

**Comment by ShikiSuen** [comment]
@zonble 我想到一個鬼方法，您權當胡鬧好了。
在 apple bopomofo keyboard layout 的基礎上，往小麥注音裡面加裝一個按鍵翻譯模組、將傳入的注音文先換成美規鍵盤的按鍵佈局訊號、再交給 Formosa 處理。
這樣順便將 dvorak 等特殊西文鍵盤佈局的支援工作轉嫁給 macOS。

這樣的話，理論上是否行得通？如果能做到的話，macOS 內建的螢幕鍵盤就能用了。

**Comment by zonble** [comment]
我應該一開始就有跟你提過，你可以考慮把 1. 注音符號翻譯回英文 2. 跳過 libFormosa 的鍵盤讓 bpmf reading 處理注音符號。不過

1. 無法支援 dvorak 鍵盤，因為你現在的鍵盤就是 Apple 注音鍵盤
2. 大千排列以外的配置也需要考慮

**Comment by ShikiSuen** [comment]
@zonble 抱歉我健忘症又犯了。
其實我的鍵盤是美規（除了近年來的 MacBook Pro 加拿大、大陸、日本客製化機種可以選注音鍵盤），一直都盲打注音。
Apple 的 bopomofo keyboard layout 理論上是如此是會動態地從 dvorak 等異種英數鍵盤翻譯成大千的（可能需要實證）。
倚天等其他鍵盤的佈局，一個追加的 layout 檔案可以搞定。

這個我回頭有時間弄一下。我先同步完 upstream 的修改。

**Comment by ShikiSuen** [comment]
這個討論串的內容的後續話題請洽這篇 discussion：
https://github.com/openvanilla/McBopomofo/discussions/248
