### ISSUE TITLE
選字 - 下鍵還沒放開前，希望這時候就能選字

### ISSUE THREAD

**Issue by salagadoola** [openvanilla/McBopomofo#76]
我平常的操作方法是：
1. 在小麥輸入法裡按下 shift + "-"
2. 按 ↓ 叫出選字列表
3. 按 "2" 選擇刪節號

但是打快一點的話，就會在 ↓ 還沒完全放開的時候按下 "2"，這時候會出現 "—2" 而不是 "…"。

希望在 ↓ 還沒放開前就能用數字選字。

**Comment by zonble** [comment]
從輸入法開發的角度，我們對這個問題無能為力…。

鍵盤上面鍵入了什麼，是 macOS 先收到之後，才會通知輸入法的。這個問題看起來，是 macOS 先把 2 送過來，才把往下的按鍵送給輸入法，從輸入法的角度來看，我們分不出到底是先按下了下還是 2。

**Comment by ShikiSuen** [comment]
你是想做成 RIME / Squirrel 那樣？但 RIME / Squirrel 不支援並擊注音欸、他們專案主管也非常不想把並擊注音做得完美。
