### ISSUE TITLE
請問如何關掉升級提示?

### ISSUE THREAD

**Issue by benpptung** [openvanilla/McBopomofo#80]
降回 0.9.7 後，一直出現升級提示，請問要如何關掉升級提示呢？謝謝您，小麥輸入法真的很好用，只可惜 0.9.8 真的很不適應。

P.S. 0.9.8 的不適應主要問題是:
0.9.8，在打逗號 ( shift + , ) 時，如果下個字是 ㄓ發音，因為還在選字模式，會讓逗號消失，而選到第 5 個字。因為等於選到 5, 打的很不順。

**Comment by lukhnos** [comment]
1.0 版可從偏好設定中關閉版本檢查: https://github.com/openvanilla/McBopomofo/releases/tag/1.0
