### ISSUE TITLE
新版本0.9.6.8對Mac的繁簡轉換功能有了障礙

### ISSUE THREAD

**Issue by milkycoffee** [openvanilla/McBopomofo#81]
桌機更新後，原來右鍵的"繁簡轉換"用不了，後來發現問題出在標點符號：只要文字中沒有標點符號就沒有問題了。

由於工作關係，本人每天要大量地寫好文章再轉成簡體，不太可能留著標點符號不打，轉換了補回。

至於另一台Macbook，我刻意不更新，結果即使包括標點符號也能進行"繁簡轉換"。我猜這樣就證實是新版本的問題了。

現在想把桌機降回舊版（即使有惱人的更新通知），如果上術情況改變了請告知，讓我安心再次更新！

但最後還是想讚美一下，這東西是即使付費也值得的！

**Comment by mjhsieh** [comment]
This is likely something to do with the macOS itself, I should have closed this, sorry for the late notice. 

We won't fix this, but we will look at the requirement of making a conversion filter ourselves if resource is available.

**Comment by ShikiSuen** [comment]
那就給這輸入法內建簡化字輸出的功能吧，畢竟 macOS 的服務不是所有應用程式都可以用的。
既然在宣傳時號稱「Mac 版的新酷音」，那 PC 版新酷音本來就有的轉簡輸出不做過來也太令人失望。

**Comment by mjhsieh** [comment]
我在此鄭重澄清，我們從來沒有在宣傳的時候提到新酷音，我從來沒講過「 Mac 版的新酷音」的這種話。如果你發現哪裡有人這樣宣稱，那絕對不是從這個專案出來的。

**Comment by ShikiSuen** [comment]
收到，估計是我幾年前看到的宣稱有誤。我需要另行起草一份 Feature Request 嗎？

**Comment by mjhsieh** [comment]
https://github.com/openvanilla/McBopomofo/issues/24

**Comment by ShikiSuen** [comment]
我找到消息源頭了（也可能是我理解的問題）：
https://www.openvanilla.org/
這個網頁明文曰：`注音輸入法（包括傳統注音以及自動選字注音）的使用者，可安裝「小麥注音」。`
問題是 OpenVanilla 內建漢字簡化輸出功能「Traditional Chinese to Simplified Chinese」：
![image](https://cloud.githubusercontent.com/assets/3164826/21573516/82a011c2-cea2-11e6-9a0d-88380e8e71c1.png)
而小麥注音沒有，這是我所失望的地方。

**Comment by ShikiSuen** [comment]
雅虎奇摩注音在新的 macOS 系統上無法正常使用；
光劍注音的詞庫直接繼承了鼠鬚管全部的缺點、且前者仍不支持傳統的大千聲韻併擊習慣；
macOS 內建注音的詞庫摻雜著大量簡轉繁所致的錯誤組詞用字搭配、以及粵語用字，全都是地雷；
新自然輸入法的詞庫十幾年沒更新過，也會出現很多錯誤的組詞用字搭配；
而 OpenVanilla 自 1.x 起不再支援新酷音、直接讓大家用小麥注音，這直接斷了大家就漢字簡化輸出這方面的選擇。

總之還是希望小麥注音能在漢字簡化輸出這方面優先做些什麼。

**Comment by milkycoffee** [comment]
有關繁簡部份容我插一下：現在已經沒有問題，也可能是Mac OS自己完善了。可以整篇打完繁體，不管那一種標點符號，全選按右鍵，直接選底下'Convert Text to Simplified Chinese"；或，如果文中參進繁簡共用的字，右鍵->"Services"->"Convert Text to Simplified Chinese"

**Comment by ShikiSuen** [comment]
@milkycoffee macOS 就這兩個功能而言有熱鍵設定的。
以漢字簡化為例：CMD+CTRL+SHIFT+ALT+C
轉換為正體中文（可能會有錯誤，但錯誤率並不高）：CMD+CTRL+SHIFT+C。

不過，這套轉換系統會自以為是地將直角引號轉換成西文引號（會在諸如知乎等網站造成不便），
且不是所有 macOS 應用都能用這套服務就是了（比如 Microsoft Word），
所以還是需要輸入法本身來支援這種功能（就像奇摩輸入法那樣）。

**Comment by ShikiSuen** [comment]
This push request from Zonble solves this issue:
https://github.com/openvanilla/McBopomofo/pull/167
