### ISSUE TITLE
McBopomofo is disabled in Twitter.app

### ISSUE THREAD

**Issue by timdream** [openvanilla/McBopomofo#84]
升級到 10.9 之後，用 Mac Twitter.app 時無法切換到小麥注音。Input Sources 裡面是灰色的。

![twitter](https://f.cloud.github.com/assets/93093/2059593/a4d955c0-8bbe-11e3-9f4b-88ce75f5111a.png)

有什麼 Workaround 嗎？

**Comment by AceChenX** [comment]
我也遇到類似的問題，在 iTerm2 下沒辦法切到小麥輸入法，然後手動搬到 `/Library/Input\ Methods/` 就可以了。
_macOS 10.13.1 / McBopomofo 0.9.9_

**Comment by zonble** [comment]
這個問題現在整理在 Wiki 中

---
小麥注音圖示在輸入法選單上變成灰色，無法切換過去，怎麼辦？

這種情況最常發生在一些企業機構配發的工作機，而且通常終端機 (Terminal.app) 程式正在執行。

請點選「終端機」選單，關閉「加密的鍵盤輸入」選項，小麥注音就會正常出現在輸入法選單上。英文語系的用戶可以從 "Terminal > Secure Keyboard Entry" 關閉該選項。

**Comment by yurenju** [comment]
我的電腦不是企業配發的也有這個問題，我記得舊版也發生過，這幾週下載新版的也有一樣問題

**Comment by lukhnos** [comment]
@yurenju 請問是指在 Twitter app 裡無法使用小麥注音嗎？

我裝了 Twitter 在 Mac App Store 上的官方 app (8.97 版) 配合小麥注音 2.0.1，是可以用的。請試試看：

1. 如果單獨執行 Twitter app 時（也就是說，當你按 Cmd-Tab 切換程式時，只看得到 Finder 跟 Twitter），小麥注音是否可以使用—也就是說，看看是否 Twitter 會因為有其他應用程式而停用第三方輸入法？
2. 如果只剩 Twitter 單獨執行仍然有此現象，恐怕得請提供更多資訊了，例如 macOS 版本，是否有裝其他 system extension 等等。

**Comment by yurenju** [comment]
@lukhnos 我目前有遇到兩個問題：
1. 小麥注音 disable：在任何 app 都會遇到，不過把 terminal 「加密的鍵盤輸入」開啟再關閉後沒發生過了
2. 選了小麥注音但是不能輸入：在任何 app 都會遇到，打字的時候不會出現任何注音，完全無法使用，從輸入法中移除再加回來也沒辦法解決

所以跟原本的 Twitter app 才會遇到的問題不太一樣了。

**Comment by lukhnos** [comment]
@yurenju 兩個想法：

1. 首先，這跟 Twitter app 遇到的情況不完全一樣，是否可以請你開一個新的 ticket 在那裡描述狀況？
2. 你上面說的第二個狀況（選了小麥注音但是不能輸入），是在第一個狀況（小麥注音 disable）時同一時期發生的，還是是在第一個狀況排除之後，新遇到的狀況？再來，這種情況有多常發生？例如說，小麥注音現在可以正常選取了，但是任何一個 app 都不能用？還是說小麥注音可以正常選取了，但是在任何 app 都（偶爾？經常？）遇到選了小麥注音不能輸入的狀況？

可以的話，請一併告知你的 OS 版本、機種 (主要想知道是不是 Apple Silicon macOS 才有的問題)、通常在使用的 app 有哪些（如果方便透露）。

**Comment by yurenju** [comment]
@lukhnos 他現在又正常了，等我下次出現的時候再來把詳細的情形記錄下來開 issue，感謝。
