### ISSUE TITLE
可否新增類似新酷音的「in place 創造新詞」功能

### ISSUE THREAD

**Issue by red010182** [openvanilla/McBopomofo#85]
新酷音裡面最棒的一個功能，就是打字的時候，可以按「ctrl + 數字鍵」來新增游標前N個字作為一個「新詞」，這個功能在輸入人名、特殊名詞時非常好用。

用簡單的方法讓使用者可以自訂新詞，這可以很大程度地加速演算法自動學習的過程，也能夠更完美的customize

**Comment by ShikiSuen** [comment]
他們不會聽的，現在這個專案他們也就只多是針對新系統相容性維護一下就算了。
