### ISSUE TITLE
Toneless and word prediction 

### ISSUE THREAD

**Issue by asoksevil** [openvanilla/McBopomofo#95]
Hey everyone.

Being used to type Zhuyin on my iPhone iOS 9 I realized the toneless and word prediction works quite well. Does anybody know if McBopomofo or any other input method has this functionality enable for Macs?

Thanks

**Comment by asoksevil** [comment]
http://key101.com

Has a very interesting input method. It has an auto learning system and although it is buggy it does allow you to type without tone and with word prediction just as if you were using an Android or iOS version.

I would love mcbopomofo to have this.

**Comment by ShikiSuen** [comment]
@asoksevil 您想要搜狗拼音/中文之星智能狂拼那樣的簡拼注音的話，可能用 RIME Squirrel 會比較快：https://www.facebook.com/rime.tw/
但其實這並沒有很快，因為這種模式對注音的融錯能力為零。倒是在觸摸螢幕的輸入條件下確實比大千聲韻並擊注音快就是了。

在使用物理鍵盤敲字時，唯有松下漢音、微軟新注音、TSF新酷音、奇摩注音這種真正的大千聲韻並擊，才是讓長篇輸入速度保持穩定的不二法寶。可惜 RIME 作者佛振個人對這種容錯設計非常之鄙視。

P.S.: 我 2002 年開始用智能狂拼，2006 年換搜狗拼音，2007 年底換微軟新注音（拼音模式），2010 年夏天接觸大千聲韻並擊、自此盲打大千聲韻至今（2012 年換 mac 之後用奇摩注音至去年年底為止）。拼音我是再也用不來了，對搜狗那樣的簡拼式注音也完全無法適從。
