### ISSUE TITLE
Be able to switch English/Chinese input languages by shift key

### ISSUE THREAD

**Issue by cldotdev** [openvanilla/McBopomofo#98]
It would be great if the shift key is an option to switch input languages.

**Comment by ShikiSuen** [comment]
您可以直接使用 Caps Lock 切換。

**Comment by Clifford-Yen** [comment]
除了因為 Windows 習慣以外，我想要提出另一個支持以 shift 切換的理由：Caps lock delay。

我目前其實反而是習慣用 caps lock 來中英切換了，但是 caps lock delay 一直是 MacBook 從以前到現在的大問題 (worst feature ever IMO)，過往還可以利用 Karabiner 移除掉這個延遲，但自從 Mojave 將 SIP 修改得更為嚴格之後，Karabiner 目前基本上無能為力。除非將 SIP 整個關掉並利用 Karabiner 移除掉 caps lock delay，不然我使用小麥注音打字時以 caps lock 切換中英輸入的成功率大約只有 3 成。建議作者真的可以考慮看看提供以 shift 作為中英輸入切換鍵的選項。

**Comment by ShikiSuen** [comment]
@Clifford-Yen 
請嘗試用這個方法移除 CapsLock Delay：
https://www.quora.com/How-do-you-turn-off-the-caps-lock-delay-feature-on-a-Mac

**Comment by Clifford-Yen** [comment]
@ShikiSuen 謝謝你的回覆，不過所有關於移除CapsLock Delay的方法我都試過了。你說的這個方法以往是適用的，但至少在最新版版本的Mojave (10.14.6 Security Update 2020-004) 中已經沒有作用（我近日才從 High Sierra 升級至 Mojave）

**Comment by ShikiSuen** [comment]
@Clifford-Yen 我在 Catalina 系統下並未重現 Caps Lock Delay 的 Bug。我有安裝專門的 Caps Lock 指示軟體，測試發現這個按鍵是即時生效的。我的電腦是 mac mini，系統是 macOS 10.15.6，用 USB 外接最新款的 Magic Keyboard 2。

**Comment by Clifford-Yen** [comment]
@ShikiSuen 也許是因為外接鍵盤並不受影響。MacBook 的內建鍵盤的話，無論在任何作業系統底下都有同樣的問題

**Comment by Clifford-Yen** [comment]
更新一下，我 Karabiner 失效的問題終於解決了，可以參考[這邊](https://github.com/pqrs-org/Karabiner-Elements/issues/2373)。所以目前我沒有切換的問題了，不過還是蠻支持加入以 shift 切換中英輸入當作選項的。
