### ISSUE TITLE
在 1Password 6 填寫表單時無法切換小麥注音

### ISSUE THREAD

**Issue by cldotdev** [openvanilla/McBopomofo#99]
如下圖，打開 1Password 6 的表單時，無法切換成小麥注音：
<img width="392" alt="1password" src="https://cloud.githubusercontent.com/assets/2265716/12848994/03c5f562-cc58-11e5-864a-7dadd1adbdac.png">

此表單開啟的狀態下，所有其他應用程式亦無法切換成小麥注音。

<img width="250" alt="2016-02-05 22 32 32" src="https://cloud.githubusercontent.com/assets/2265716/12849066/83addb8c-cc58-11e5-8498-29bc9ed7d179.png">

**Comment by YuerLee** [comment]
我也碰到一樣的問題。

版本資訊：

- 小麥注音： 0.9.7（768）
- macOS: 10.12.2（16C67）
- 1Password 6.5.3 (653001) from Mac App Store

補充一下，內建輸入法是可以的。

<img width="308" alt="2017-01-05 15 58 57" src="https://cloud.githubusercontent.com/assets/2075566/21672847/04106d44-d360-11e6-9361-d6fb36377789.png">

**Comment by ShikiSuen** [comment]
當前輸入法沒能獲取管理員權限所致。我有個解決思路：

開啟終端機，執行`sudo su`進入根管理員模式，
然後將`~/Library/Input Methods`內的小麥注音藉由該模式挪至`/Library/Input Methods`目錄下。

**Comment by YuerLee** [comment]
感謝 @ShikiSuen，此法可行。

1. `sudo mv ~/Library/Input\ Methods/McBopomofo.app/ /Library/Input\ Methods/`
2. 登出登入

**Comment by ShikiSuen** [comment]
@passerbyid 可能是我愚昧吧，竊以為 以 sudo 前綴執行命令的實際權限不如 sudo su 模式來得高。

**Comment by ShikiSuen** [comment]
另外這問題發生真的不奇怪，特別是來自 MAS 的應用對副廠輸入法的權限管理更為敏感。

**Comment by yan12125** [comment]
在LINE遇到相同問題，用@ShikiSuen的方法解決了，感謝！

MAS是指Mac App Store？

**Comment by ShikiSuen** [comment]
@yan12125 MAS = Mac App Store.

**Comment by cldotdev** [comment]
感謝 @ShikiSuen 回應，據他的解釋及我的理解，是跟 1Password 沒能把控好 macOS 的 SecureEventInput 功能應該要在什麼情況下啟用和禁用有關，一般在啟用的情況下系統並不允許叫出第三方輸入法。

這問題跟 1Password 較有關係，故關閉此 issue。
